import { DirectoryControl, ValueControl } from './UserInputForm'
import { useRef, useState } from 'react'
import { Button, Empty, Field, Notice, Section, Tag } from '../components'
import { applyDecision, attachmentIssues, empty, exampleValue, fieldApplies, initialInputValues, inputIssues, missingPresentation, newInputField, peopleDirectory, type DecisionState, type InputField, type InteractionConfig } from './interaction-model'
import './interaction.css'

type Values = Record<string, unknown>
const messageLabels = { configured: '当前输入输出联动', text: '文字追问', clarify_choice: '候选澄清', form: '信息表单', data_select: '数据候选', confirm: '执行前确认', review: '逐人审核', file_request: '补充附件', authorization_request: '工具授权', status: '运行与等待', result: '交付结果', unsupported: '不支持的消息' }
type Mode = keyof typeof messageLabels
export function InteractionPreview({ value, name, readOnly = false, configDigest }: { value: InteractionConfig; name: string; readOnly?: boolean; configDigest?: string }) {
  return <PreviewSession key={`${JSON.stringify(value)}:${configDigest ?? ''}:${name}`} value={value} name={name} readOnly={readOnly} />
}
function PreviewSession({ value, name, readOnly }: { value: InteractionConfig; name: string; readOnly: boolean }) {
  const [mode, setMode] = useState<Mode>('configured'); const [generation, setGeneration] = useState(0)
  return <div className="interaction-preview"><Section title="交互预览" description={`${name || '当前专家'} · 使用当前保存配置，刷新或修改配置后重新开始。`}><Notice>交互模拟，不调用模型或业务系统。{readOnly ? '当前配置只读，仍可操作以下模拟样例。' : '内容、人员、文件与业务动作均为示例。'}</Notice><div className="interaction-preview-toolbar"><Field label="交互样例"><select value={mode} onChange={e => { setMode(e.target.value as Mode); setGeneration(v => v + 1) }}>{Object.entries(messageLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Button onClick={() => setGeneration(v => v + 1)}>重置样例</Button></div><Sample key={`${mode}-${generation}`} mode={mode} value={value} name={name} /></Section></div>
}
function Sample({ mode, value, name }: { mode: Mode; value: InteractionConfig; name: string }) {
  const [text, setText] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [complete, setComplete] = useState(false); const [error, setError] = useState(''); const [none, setNone] = useState(false); const [granted, setGranted] = useState<boolean>(); const [status, setStatus] = useState('运行中'); const [stage, setStage] = useState(1)
  const envelope = { schema_version: '1.0', interaction_id: `demo-${mode}`, task_id: 'demo-task', run_id: 'demo-run', agent_id: 'demo-agent', agent_version_id: 'demo-saved-config', type: mode === 'configured' ? 'form' : mode, payload: { demo: true } }
  const doSubmit = (valid: boolean, message: string) => { if (!valid) { setError(message); return } setError(''); setComplete(true) }
  if (mode === 'configured' || mode === 'form') return <ConfiguredForm value={value} name={name} forceForm={mode === 'form'} />
  if (mode === 'confirm') return <DecisionCard interactionId="demo-confirm" recipient="业务写操作" review={false} value={value} />
  if (mode === 'review') {
    const recipients = value.output.recipients.length ? value.output.recipients : ['lin', 'zhou']
    return <div><p className="campus-hint">{value.output.recipients.length ? '按已配置接收人展示' : '未配置接收人，以下两位仅作独立审核样例'}。每项内容单独确认，操作一人不影响其他人。</p>{recipients.map(recipient => <DecisionCard key={recipient} interactionId={`demo-review-${recipient}`} recipient={peopleDirectory.find(p => p.id === recipient)?.name ?? recipient} review value={value} />)}</div>
  }
  if (mode === 'file_request') return <AttachmentCard value={value} />
  return <div className="interaction-sample"><div className="interaction-sample-label"><Tag>固定样例</Tag><span>{mode}</span></div>
    {mode === 'text' && <><h3>还需要补充哪些信息</h3><p>现有材料无法确定处理范围，请补充任务目标和依据。没有材料支持的结论将保留待核对状态。</p><Field label="补充任务信息"><textarea value={text} disabled={complete} onChange={e => setText(e.target.value)} /></Field><Button disabled={complete} onClick={() => doSubmit(!!text.trim(), '请先填写补充信息')}>提交补充</Button>{complete && <Notice tone="success">已记录补充内容，模拟进入下一步。没有运行真实问答。</Notice>}</>}
    {mode === 'clarify_choice' && <><h3>请选择本次要办理的事项</h3><p>以下是固定澄清样例，不代表已匹配真实专家。</p>{['整理会议安排', '核对材料', '没有适合的选项'].map(item => <label key={item} className="campus-check"><input type="radio" name="clarify" value={item} checked={selected[0] === item} disabled={complete} onChange={() => setSelected([item])} />{item}</label>)}<Field label="补充说明"><textarea value={text} disabled={complete} onChange={e => setText(e.target.value)} /></Field><Button disabled={complete} onClick={() => doSubmit(!!selected.length && (selected[0] !== '没有适合的选项' || !!text.trim()), '请选择候选；无适合选项时请补充说明')}>确认选择</Button>{complete && <Notice tone="success">已记录「{selected[0]}」{text ? `：${text}` : ''}，完成本次澄清模拟。</Notice>}</>}
    {mode === 'data_select' && <><h3>选择可用场地</h3><p>候选来自本地示例目录；失效场地不能确认。</p><DirectoryControl field={{ ...newInputField(), label: '场地', type: 'room' }} value={selected[0] ?? ''} onChange={v => setSelected([String(v)])} disabled={complete || none} /><label className="campus-check"><input type="checkbox" checked={none} disabled={complete} onChange={e => { setNone(e.target.checked); setSelected([]) }} />没有适合的候选</label>{none && <Field label="调整需求"><textarea value={text} onChange={e => setText(e.target.value)} disabled={complete} /></Field>}<Button disabled={complete} onClick={() => doSubmit(none ? !!text.trim() : !!selected[0], '请选择场地，或说明没有合适候选的原因')}>提交场地选择</Button>{complete && <Notice tone="success">{none ? '已保留调整需求，可重置后重新选择。' : '已保存场地选择（模拟），尚未预约。'}</Notice>}</>}
    {mode === 'authorization_request' && <><h3>读取日历前需要授权</h3><p>示例日历服务 · 仅“读取本人忙闲时间”，用于安排会议；不授权其他工具。</p><dl className="facts"><div><dt>具体工具</dt><dd>读取日历（只读）</dd></div><div><dt>数据范围</dt><dd>当前模拟用户的日历</dd></div></dl><div className="interaction-actions"><Button disabled={granted !== undefined} onClick={() => setGranted(true)}>模拟同意授权</Button><Button disabled={granted !== undefined} onClick={() => setGranted(false)}>拒绝授权</Button></div>{granted !== undefined && <Notice tone={granted ? 'success' : 'warning'}>{granted ? '仅此工具获得本次样例许可，未连接真实服务。' : '保持未授权；依赖此工具的步骤不能继续。'}<Button onClick={() => setGranted(undefined)}>返回授权核对</Button></Notice>}</>}
    {mode === 'status' && <><h3>任务状态 · {status}</h3><p>示例进度：{stage} / 3。已完成的材料摘要会保留。</p><progress max={3} value={stage} aria-label="模拟任务进度" /><div className="interaction-actions"><Button disabled={status !== '运行中'} onClick={() => setStatus('已暂停')}>暂停任务</Button><Button disabled={!['已暂停', '等待依赖'].includes(status)} onClick={() => setStatus('运行中')}>继续任务</Button><Button disabled={['已取消', '已完成'].includes(status)} onClick={() => setStatus('已取消')}>取消任务</Button><Button disabled={status !== '运行中'} onClick={() => { if (stage === 2) setStatus('已完成'); setStage(v => Math.min(3, v + 1)) }}>推进模拟步骤</Button><Button disabled={status !== '运行中'} onClick={() => setStatus('等待依赖')}>演示依赖不可用</Button></div>{status === '等待依赖' && <Notice tone="warning">校内示例服务暂不可用；保留已完成步骤，恢复后可继续。</Notice>}{status === '已取消' && <Notice>已取消后续步骤；已整理的材料摘要保留。未执行任何外部写入。</Notice>}</>}
    {mode === 'result' && <ResultCard value={value} name={name} />}
    {mode === 'unsupported' && <><Notice tone="warning">当前界面尚不支持此消息版本。请查看原始内容或返回选择其他样例；没有业务确认按钮。</Notice><pre>{JSON.stringify({ ...envelope, schema_version: '99.0', type: 'future_message', payload: { text: '来自未来版本的示例文本' } }, null, 2)}</pre></>}
    {error && <Notice tone="error">{error}</Notice>}<details className="interaction-raw"><summary>查看样例关联信息</summary><pre>{JSON.stringify(envelope, null, 2)}</pre></details>
  </div>
}

function ConfiguredForm({ value, name, forceForm }: { value: InteractionConfig; name: string; forceForm: boolean }) {
  const fields = value.input.fields
  const [values, setValues] = useState<Values>(() => ({ ...initialInputValues(value), ...Object.fromEntries(fields.filter(f => f.source === 'agent_prefill').map(f => [f.key, exampleValue(f)])) }))
  const [confirmed, setConfirmed] = useState<string[]>([]); const [issues, setIssues] = useState<string[]>([]); const [done, setDone] = useState(false); const [text, setText] = useState(''); const [started, setStarted] = useState(false)
  const presentation = missingPresentation(value, values, confirmed)
  const visible = fields.filter(f => fieldApplies(f, values, fields) && (started || forceForm || value.input.entryMode === 'form' || value.input.entryFields.includes(f.key) || f.requirement === 'conditional'))
  const submit = () => { setStarted(true); const errors = inputIssues(value, values, confirmed); if (!fields.length && !text.trim()) errors.push('请填写任务信息'); setIssues(errors); if (!errors.length) { setValues(Object.fromEntries(Object.entries(values).filter(([key]) => { const field = fields.find(f => f.key === key); return field && fieldApplies(field, values, fields) }))); setDone(true) } }
  const update = (f: InputField, input: unknown) => { setValues(old => { const next = { ...old, [f.key]: input }; for (const other of fields) if (!fieldApplies(other, next, fields)) delete next[other.key]; return next }); setConfirmed(old => old.filter(key => key !== f.key)); setIssues([]) }
  return <div className="interaction-sample"><div className="interaction-sample-label"><Tag>{forceForm ? '表单样例' : '当前配置联动'}</Tag><span>{forceForm ? 'form' : started ? presentation === 'ready' ? '可以继续' : presentation : '入口信息'}</span></div>{!fields.length && <Notice>当前没有结构化字段，使用自由文字输入。可在输入分区添加字段后再验证人员、时间与条件联动。</Notice>}{fields.length > 0 && <p className="campus-hint">{started && presentation === 'text' ? '请补充以下文字信息。' : started && presentation === 'data_select' ? '请从可用候选中选择；没有合适候选时可调整字段或重置样例。' : '按当前字段配置填写。条件变化会清除不再适用的回答。'}</p>}
    {value.input.instructions && <p className="interaction-preparation-note">{value.input.instructions}</p>}
    {!fields.length && <Field label="任务信息"><textarea value={text} disabled={done} onChange={e => setText(e.target.value)} /></Field>}
    {visible.map(f => <div className="interaction-input-item" key={f.id}><div className="interaction-field-label"><strong>{f.label}{f.requirement !== 'optional' ? ' *' : ''}</strong><Tag>{f.source === 'agent_prefill' ? 'AI 推断，请确认' : f.source === 'lookup' ? '模拟目录' : '用户填写'}</Tag></div><ValueControl config={value} field={f} value={values[f.key]} onChange={input => update(f, input)} disabled={done} />{f.source === 'agent_prefill' && !empty(values[f.key]) && <label className="campus-check"><input type="checkbox" checked={confirmed.includes(f.key)} disabled={done} onChange={e => setConfirmed(old => e.target.checked ? [...old, f.key] : old.filter(key => key !== f.key))} />确认{f.label}无误</label>}</div>)}
    {!done && <div className="interaction-actions"><Button variant="primary" onClick={submit}>{started ? '提交补充信息' : '提交输入'}</Button>{fields.length > 0 && <Button onClick={() => { setStarted(true); setValues(Object.fromEntries(fields.map(f => [f.key, exampleValue(f)]))); setConfirmed([]); setIssues([]) }}>填入示例值</Button>}<Button onClick={() => { setValues({}); setConfirmed([]); setStarted(true); setIssues([]) }}>清空并查看追问</Button></div>}
    {issues.length > 0 && <Notice tone="error"><ul>{issues.map(issue => <li key={issue}>{issue}</li>)}</ul></Notice>}
    {done && <><Notice tone="success">输入已提交并只读；本次只完成字段校验，没有模型运行。</Notice><ResultCard value={value} name={name} values={values} /></>}
  </div>
}

function DecisionCard({ interactionId, recipient, review, value }: { interactionId: string; recipient: string; review: boolean; value: InteractionConfig }) {
  const initial: DecisionState = { interactionId, contentVersion: 1, status: 'pending', keys: [], transitions: 0 }
  const [state, setState] = useState(initial); const live = useRef(initial); const [content, setContent] = useState(value.output.requirements || '整理会议方案，待审核后确认；尚未发送邀请。'); const [savedContent, setSavedContent] = useState(content); const [error, setError] = useState(''); const lastAction = useRef<{ key: string; contentVersion: number; decision: 'confirm' | 'reject' | 'modify' } | null>(null)
  const perform = (decision: 'confirm' | 'reject' | 'modify', stale = false, repeat = false, replacement?: string) => {
    if (decision !== 'modify' && content !== savedContent) { setError('有未保存的内容修改，请先保存修改并更新版本'); return }
    const action = repeat && lastAction.current ? lastAction.current : { key: `${interactionId}-${live.current.contentVersion}-${decision}-${stale ? 'old' : 'current'}`, contentVersion: stale ? 0 : live.current.contentVersion, decision }
    try { const next = applyDecision(live.current, action); live.current = next; setState(next); lastAction.current = action; if (decision === 'modify') { setSavedContent(replacement ?? content); if (replacement !== undefined) setContent(replacement) } setError(repeat ? '已识别重复提交，状态没有再次推进。' : '') } catch (e) { setError((e as Error).message) }
  }
  return <article className="interaction-decision"><div className="interaction-heading"><h3>{review ? `审核给${recipient}的内容` : '执行前确认'}</h3><Tag>{state.status === 'pending' ? '待确认' : state.status === 'confirmed' ? '已确认' : '已拒绝'} · 内容 v{state.contentVersion}</Tag></div><p className="campus-hint">{review ? '审核内容与该接收人独立关联。' : '待执行：写入示例业务系统。确认只改变本地状态。'}修改内容会产生新版本，旧确认不能继续使用。</p><Field label={`${recipient}的待确认内容`}><textarea value={content} disabled={state.status !== 'pending'} onChange={e => setContent(e.target.value)} /></Field><details className="campus-inset"><summary>查看来源与事实核对</summary><p>示例来源：用户提交的会议材料 · 第 1 段。以下核对结果来自配置样例。</p><FactResults value={value} /></details><div className="interaction-actions"><Button variant="primary" disabled={state.status !== 'pending'} onClick={() => perform('confirm')}>{review ? `批准${recipient}的内容` : '确认执行（模拟）'}</Button><Button disabled={state.status !== 'pending'} onClick={() => perform('modify')}>保存修改并更新版本</Button>{review && <Button disabled={state.status !== 'pending'} onClick={() => perform('modify', false, false, `${savedContent}\n重新整理的示例内容`)}>重新生成（模拟）</Button>}<Button disabled={state.status !== 'pending'} onClick={() => perform('reject')}>拒绝{review ? recipient : '操作'}</Button></div><details className="interaction-raw"><summary>验证旧版本与重复提交</summary><div className="interaction-actions"><Button onClick={() => perform('confirm', true)}>提交旧内容版本</Button><Button disabled={!lastAction.current} onClick={() => perform(lastAction.current?.decision ?? 'confirm', false, true)}>重复提交上次决定</Button></div><pre>{JSON.stringify({ schema_version: '1.0', interaction_id: interactionId, task_id: 'demo-task', run_id: 'demo-run', agent_id: 'demo-agent', agent_version_id: 'demo-saved-config', type: review ? 'review' : 'confirm', content_version: `content-v${state.contentVersion}`, payload: { recipient: review ? { id: interactionId.replace('demo-review-', ''), name: recipient } : undefined, content: savedContent }, transitions: state.transitions }, null, 2)}</pre></details>{error && <Notice tone="warning">{error}</Notice>}{state.status === 'confirmed' && <Notice tone="success">此项已确认；外部动作仍为“未执行”。</Notice>}{state.status === 'rejected' && <Notice>此项已拒绝，后续模拟动作停止；其他审核项不受影响。</Notice>}</article>
}
function FactResults({ value }: { value: InteractionConfig }) { return value.output.factChecks.length ? <ul>{value.output.factChecks.map(check => <li key={check.id}>{value.output.fields.find(f => f.key === check.outputKey)?.label ?? check.outputKey}：{check.result === 'match' ? '一致' : check.result === 'different' ? '存在差异，需处理' : '未核实，待确认'} · {check.source === 'input' ? value.input.fields.find(f => f.key === check.inputKey)?.label : '模拟业务目录'}</li>)}</ul> : <p>未配置关键事实比对；不声明事实已经核实。</p> }
function ResultCard({ value, name, values = {} }: { value: InteractionConfig; name: string; values?: Values }) {
  const format = value.output.format; const hasUnresolved = value.output.factChecks.some(f => f.result !== 'match')
  const [approved, setApproved] = useState(false)
  return <div className="interaction-result"><Tag>模拟交付结果</Tag><section><h3>01 任务概述</h3><p>{name}：{value.output.requirements || '根据输入整理结果，缺少依据时说明待核对项。'}</p></section><section><h3>02 交付物</h3>{['document', 'pdf'].includes(format) ? <div className="interaction-file-card"><strong>{name || '专家'}成果示例.{format === 'pdf' ? 'pdf' : 'docx'}</strong><small>文件卡示例，尚未生成真实文件</small></div> : format === 'json' ? <pre>{JSON.stringify(Object.fromEntries(value.output.fields.map(field => [field.key, exampleValue(field)])), null, 2)}</pre> : format === 'table' && value.output.fields.length ? <div className="table-scroll"><table className="data-table"><thead><tr>{value.output.fields.map(f => <th key={f.key}>{f.label}</th>)}</tr></thead><tbody><tr>{value.output.fields.map(f => <td key={f.key}>{String(exampleValue(f))}</td>)}</tr></tbody></table></div> : <p>{value.output.fields.length ? value.output.fields.map(f => `${f.label}：${String(exampleValue(f))}`).join('；') : '成果正文示例。内容尚未经过真实模型处理。'}</p>}{value.output.sections.map(section => <div key={section.id}><strong>{section.title || '待命名章节'}</strong><p>此处为该章节的示例内容，真实交付待执行。</p></div>)}{Object.keys(values).length > 0 && <details><summary>查看本次输入</summary><ul>{Object.entries(values).map(([key, value]) => <li key={key}>{key}：{typeof value === 'object' && value !== null && 'name' in value ? String(value.name) : String(value)}</li>)}</ul></details>}<details><summary>查看模拟来源定位</summary><p>用户提供材料 · 示例第 1 段；此处为本地来源示例，没有读取真实文件。</p></details></section><section><h3>03 完成情况</h3><p>内容：已生成示例 · 审核：{approved ? '已确认（模拟）' : value.output.deliveryConfirm || format === 'recipient' ? '待审核' : '未要求交付确认'} · 外部动作：未执行</p></section><section><h3>04 待处理事项</h3><FactResults value={value} /><p>{hasUnresolved ? '存在差异或未核实项，不能视作全部完成。' : '请核对真实依据；外部业务尚未生效。'}</p></section>{format === 'recipient' ? <Notice>逐人交付须分别审核，请切换“逐人审核”样例。当前不提供整批批准。</Notice> : value.output.deliveryConfirm && <Button disabled={approved || hasUnresolved} onClick={() => setApproved(true)}>确认此份交付（模拟）</Button>}</div>
}
function AttachmentCard({ value }: { value: InteractionConfig }) {
  const [files, setFiles] = useState<{ name: string; size: number; minutes?: number }[]>([]); const [errors, setErrors] = useState<string[]>([]); const [done, setDone] = useState(false)
  const select = (next: typeof files) => { setFiles(next); setErrors(attachmentIssues(next, value)); setDone(false) }
  return <div className="interaction-sample"><Tag>file_request</Tag><h3>补充任务材料</h3><p>只检查名称、类型、大小。真实音频时长需要底座解析，本原型用样例时长验证限制。</p><Field label="选择预览附件"><input type="file" multiple disabled={done} onChange={e => select([...e.target.files ?? []].map(f => ({ name: f.name, size: f.size })))} /></Field><div className="interaction-actions"><Button onClick={() => select([{ name: '说明.txt', size: 1024 }])}>载入文字附件示例</Button><Button onClick={() => select([{ name: '超限.pdf', size: 21 * 1024 ** 2 }])}>演示非音频超限</Button><Button onClick={() => select([{ name: '长录音.mp3', size: 20 * 1024 ** 2, minutes: 61 }])}>演示音频时长超限</Button><Button onClick={() => select([])}>重新选择</Button></div>{files.map((file, index) => <div className="interaction-file-card" key={`${file.name}-${index}`}><strong>{file.name}</strong><small>{(file.size / 1024 ** 2).toFixed(2)} MB{file.minutes ? ` · ${file.minutes} 分钟（示例）` : ''}</small></div>)}{errors.length > 0 && <Notice tone="error"><ul>{errors.map(e => <li key={e}>{e}</li>)}</ul></Notice>}<Button variant="primary" disabled={!files.length || errors.length > 0 || done} onClick={() => setDone(true)}>提交附件元数据</Button>{done && <Notice tone="success">已记录附件元数据；没有上传或解析内容，文件字节不会持久保存。</Notice>}</div>
}
