import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { App } from '../../../prototypes/macos-client-v2/src/App'
import { MessageAttachmentGroup } from './components/message-ui'

const scrollDescriptor = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'scrollIntoView')
beforeEach(() => {
  vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} })
  Object.defineProperty(HTMLElement.prototype, 'scrollIntoView', { configurable: true, value: vi.fn() })
})
afterEach(() => {
  cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers()
  if (scrollDescriptor) Object.defineProperty(HTMLElement.prototype, 'scrollIntoView', scrollDescriptor)
  else Reflect.deleteProperty(HTMLElement.prototype, 'scrollIntoView')
})

function navigate(label: string) {
  fireEvent.click(within(screen.getByRole('navigation', { name: '一级导航' })).getByRole('button', { name: label }))
}

function openUserMenuItem(label: string) {
  fireEvent.click(screen.getByRole('button', { name: 'Kakarrot 用户菜单' }))
  fireEvent.click(screen.getByRole('menuitem', { name: label }))
}

function openPersonalCenter() {
  openUserMenuItem('个人中心')
}

function selectCatalogAgent(name: string) {
  fireEvent.click(screen.getByRole('button', { name: `查看智能体 ${name}` }))
  fireEvent.click(within(screen.getByRole('dialog', { name: `${name}详情` })).getByRole('button', { name: '开始对话' }))
}

describe('Web prototype interaction parity', () => {
  it('validates the message form and preserves its draft and confirmed state in its own conversation', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /^Agent 产品讨论/ }))
    const form = screen.getByRole('form', { name: '补充文档需求' })
    fireEvent.click(within(form).getByRole('button', { name: '确认信息' }))
    expect(within(form).getByRole('alert')).toHaveTextContent('请填写目标读者')
    const audience = within(form).getByRole('textbox', { name: /目标读者/ })
    expect(audience).toHaveAttribute('aria-invalid', 'true')
    fireEvent.change(audience, { target: { value: '新入职的老师' } })
    fireEvent.change(within(form).getByRole('combobox', { name: '文档形式' }), { target: { value: '使用指南' } })
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    expect(screen.queryByRole('form', { name: '补充文档需求' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /^Agent 产品讨论/ }))
    expect(screen.getByRole('textbox', { name: /目标读者/ })).toHaveValue('新入职的老师')
    expect(screen.getByRole('combobox', { name: '文档形式' })).toHaveValue('使用指南')
    fireEvent.click(screen.getByRole('button', { name: '确认信息' }))
    expect(screen.getByRole('textbox', { name: /目标读者/ })).toBeDisabled()
    expect(screen.getByText('已在本次会话记录')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '归档对话 Agent 产品讨论' }))
    openUserMenuItem('归档会话')
    fireEvent.click(screen.getByRole('button', { name: '恢复对话 Agent 产品讨论' }))
    expect(screen.getByRole('textbox', { name: /目标读者/ })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '修改信息' }))
    expect(screen.getByRole('textbox', { name: /目标读者/ })).toBeEnabled()
    expect(screen.getByRole('textbox', { name: /目标读者/ })).toHaveValue('新入职的老师')
  })

  it('preserves send timestamps and groups messages across local calendar days', () => {
    vi.useFakeTimers({ toFake: ['Date'] })
    const first = new Date(2026, 8, 17, 23, 59)
    vi.setSystemTime(first)
    const { container } = render(<App />)
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '跨日第一条' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    const second = new Date(2026, 8, 18, 0, 1)
    vi.setSystemTime(second)
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '跨日第二条' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect([...container.querySelectorAll('.message-author time')].map((time) => time.getAttribute('datetime'))).toEqual([first.toISOString(), first.toISOString(), second.toISOString(), second.toISOString()])
    expect([...container.querySelectorAll('.date-divider')].map((divider) => divider.textContent)).toEqual(['2026年9月17日', '今天'])
    expect(within(screen.getByRole('region', { name: '对话' })).queryByText('刚刚')).not.toBeInTheDocument()
    expect(screen.queryByText('示例对话')).not.toBeInTheDocument()
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: /^跨日第一条\s*助理/ }))
    expect(container.querySelector('.message-author time')).toHaveAttribute('datetime', first.toISOString())
  })

  it('keeps IME confirmation and Shift+Enter separate from sending, then refocuses after send', () => {
    render(<App />)
    const input = screen.getByRole('textbox', { name: '发送消息' })
    fireEvent.change(input, { target: { value: '中文输入法消息' } })
    fireEvent.keyDown(input, { key: 'Enter', isComposing: true, keyCode: 229 })
    fireEvent.keyDown(input, { key: 'Enter', shiftKey: true })
    expect(screen.queryByRole('article', { name: 'Kakarrot的消息' })).not.toBeInTheDocument()
    fireEvent.keyDown(input, { key: 'Enter' })
    expect(screen.getByRole('article', { name: 'Kakarrot的消息' })).toHaveTextContent('中文输入法消息')
    expect(input).toHaveValue('')
    expect(input).toHaveFocus()
    expect(screen.getByRole('button', { name: '发送' })).toBeDisabled()
  })

  it('opens a keyboard-accessible user menu in the collapsed sidebar', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: '折叠左侧栏' }))
    const trigger = screen.getByRole('button', { name: 'Kakarrot 用户菜单' })
    expect(trigger).toHaveAttribute('aria-haspopup', 'true')
    fireEvent.click(trigger)
    const menu = screen.getByRole('menu', { name: /用户菜单/ })
    expect(within(menu).getAllByRole('menuitem').map((item) => item.textContent)).toEqual(['个人中心', '归档会话'])
    fireEvent.keyDown(menu, { key: 'Escape', code: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('menu')).not.toBeInTheDocument())
    openUserMenuItem('归档会话')
    expect(screen.getByRole('heading', { name: '个人中心' })).toBeInTheDocument()
    expect(within(screen.getByRole('navigation', { name: '个人中心菜单' })).getByRole('button', { name: '归档会话' })).toHaveAttribute('aria-current', 'page')
    expect(screen.getByText('暂无归档对话')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '展开左侧栏' })).toBeEnabled()
  })

  it('archives and restores a conversation with its messages, draft and attachment intact', () => {
    const { container } = render(<App />)
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '保留完整对话' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '尚未发送的内容' } })
    fireEvent.change(screen.getByLabelText('添加附件'), { target: { files: [new File(['note'], 'draft.txt')] } })
    expect(screen.queryByRole('button', { name: /^删除对话/ })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '归档对话 保留完整对话' }))
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('')
    expect(container.querySelectorAll('.conversation-row')).toHaveLength(2)
    expect(screen.queryByRole('button', { name: /^保留完整对话/ })).not.toBeInTheDocument()
    openPersonalCenter()
    const personalMenu = screen.getByRole('navigation', { name: '个人中心菜单' })
    expect(within(personalMenu).getByRole('button', { name: '基本资料' })).toHaveAttribute('aria-current', 'page')
    fireEvent.click(within(personalMenu).getByRole('button', { name: '归档会话' }))
    expect(within(personalMenu).getByRole('button', { name: '归档会话' })).toHaveAttribute('aria-current', 'page')
    expect(screen.queryByRole('table', { name: '用量记录' })).not.toBeInTheDocument()
    expect(screen.getByRole('list', { name: '归档对话列表' })).toHaveTextContent('保留完整对话')
    fireEvent.change(screen.getByRole('textbox', { name: '搜索归档对话' }), { target: { value: '不存在' } })
    expect(screen.getByText('没有匹配的归档对话')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '清空搜索' }))
    fireEvent.click(screen.getByRole('button', { name: '恢复对话 保留完整对话' }))
    expect(screen.getByLabelText('对话')).toHaveTextContent('保留完整对话')
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('尚未发送的内容')
    expect(screen.getByRole('button', { name: '移除 draft.txt' })).toBeInTheDocument()
    expect(container.querySelectorAll('.conversation-row')).toHaveLength(3)
    openUserMenuItem('归档会话')
    expect(screen.getByText('暂无归档对话')).toBeInTheDocument()
  })

  it('deletes only archived conversations after confirmation and keeps other conversations available', () => {
    render(<App />)
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '归档对话 东南亚市场研究' }))
    expect(screen.getByRole('heading', { name: '专家市场' })).toBeInTheDocument()
    openUserMenuItem('归档会话')
    fireEvent.click(screen.getByRole('button', { name: '删除对话 东南亚市场研究' }))
    let confirmation = screen.getByRole('dialog', { name: '删除对话？' })
    expect(confirmation).toHaveTextContent('无法撤销')
    fireEvent.click(within(confirmation).getByRole('button', { name: '取消' }))
    expect(screen.getByRole('list', { name: '归档对话列表' })).toHaveTextContent('东南亚市场研究')
    fireEvent.click(screen.getByRole('button', { name: '删除对话 东南亚市场研究' }))
    confirmation = screen.getByRole('dialog', { name: '删除对话？' })
    fireEvent.click(within(confirmation).getByRole('button', { name: '确认删除' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByText('暂无归档对话')).toBeInTheDocument()
    navigate('新对话')
    expect(screen.queryByRole('button', { name: /^东南亚市场研究/ })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: /^Agent 产品讨论/ })).toBeEnabled()
    openUserMenuItem('归档会话')
    expect(screen.queryByRole('button', { name: /恢复对话|删除对话/ })).not.toBeInTheDocument()
  })

  it.each([false, true])('respects reduced motion (%s) when advancing the shared attachment carousel', (reduced) => {
    vi.stubGlobal('matchMedia', (query: string) => ({ matches: reduced && query === '(prefers-reduced-motion: reduce)', media: query, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {} }))
    vi.spyOn(HTMLElement.prototype, 'scrollWidth', 'get').mockReturnValue(620)
    vi.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockReturnValue(220)
    vi.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(200)
    const { container } = render(<MessageAttachmentGroup source="user" attachments={[{ id: 'a', name: 'a.txt', detail: 'TXT' }, { id: 'b', name: 'b.txt', detail: 'TXT' }]} />)
    const rows = container.querySelector('.message-attachments__rows') as HTMLElement
    const scrollBy = vi.fn()
    Object.defineProperty(rows, 'scrollBy', { value: scrollBy })
    fireEvent.scroll(rows)
    fireEvent.click(screen.getByRole('button', { name: '查看下一份附件' }))
    expect(scrollBy).toHaveBeenCalledWith({ left: 207, behavior: reduced ? 'auto' : 'smooth' })
  })

  it('shows the student expert catalog with creation and without a contacts sidebar', () => {
    const { container } = render(<App />)
    const rail = screen.getByRole('navigation', { name: '一级导航' })
    expect(within(rail).queryByRole('button', { name: '能力' })).not.toBeInTheDocument()
    expect(within(rail).queryByRole('button', { name: '连接' })).not.toBeInTheDocument()
    navigate('专家市场')
    expect(screen.getByRole('button', { name: '专家市场' })).toHaveAttribute('aria-current', 'page')
    expect(screen.getByRole('heading', { name: '聊天记录' })).toBeInTheDocument()
    expect(container.querySelector('.prototype')).toHaveClass('campus-shell')
    expect(screen.getByRole('region', { name: '智能体目录' })).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(32)
    expect(screen.getByRole('button', { name: '创建专家' })).toBeEnabled()
    for (const name of ['学科辅导', '游戏攻略', '旅游出行', '恋爱交流', '情绪陪伴', '校园成长', '教学备课', '学生指导', '科研支持', '校务办公']) expect(screen.getByRole('region', { name })).toBeInTheDocument()
    for (const name of ['Teams 会议专员', '网络情报员', '产品经理', '政务数字化售前顾问']) expect(screen.queryByRole('button', { name: `查看智能体 ${name}` })).not.toBeInTheDocument()
    for (const name of ['新建 Agent', '设置', '招募', '创建智能体', '通讯录']) expect(screen.queryByRole('button', { name })).not.toBeInTheDocument()
    expect(screen.queryByRole('tab', { name: '专家团' })).not.toBeInTheDocument()
    navigate('新对话')
    expect(container.querySelector('.context-pane')).not.toBeNull()
    expect(screen.getByPlaceholderText('发送给助理')).toBeEnabled()
  })

  it('keeps branded navigation and drafts usable when collapsing and switching pages', () => {
    const { container } = render(<App />)
    const toolbar = screen.getByRole('banner', { name: '页面顶部栏' })
    expect(screen.getByText('西亚斯数字员工')).toBeInTheDocument()
    expect(within(toolbar).getByRole('heading', { name: '新对话' })).toBeInTheDocument()
    expect(toolbar).toHaveTextContent('助理 · 一对一对话')
    expect(container.querySelector('.rail')).toHaveClass('rail--expanded')
    expect(screen.getByRole('heading', { name: '聊天记录' })).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: '新对话' })).toHaveLength(1)
    expect(screen.queryByRole('button', { name: '消息' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '新建会话' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '折叠后保留的草稿' } })
    fireEvent.change(screen.getByRole('textbox', { name: '搜索会话' }), { target: { value: '东南亚' } })
    fireEvent.click(screen.getByRole('button', { name: '折叠左侧栏' }))
    expect(container.querySelector('.prototype')).toHaveClass('is-context-collapsed')
    expect(container.querySelector('.rail__body')).toHaveAttribute('hidden')
    expect(screen.queryByRole('textbox', { name: '搜索会话' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '展开左侧栏' }))
    expect(screen.getByRole('textbox', { name: '搜索会话' })).toHaveValue('东南亚')
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('折叠后保留的草稿')
    navigate('专家市场')
    expect(within(toolbar).getByRole('heading', { name: '专家市场' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: '聊天记录' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '折叠左侧栏' }))
    openPersonalCenter()
    expect(within(toolbar).getByRole('heading', { name: '个人中心' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '展开左侧栏' })).toBeEnabled()
    fireEvent.click(screen.getByRole('button', { name: '展开左侧栏' }))
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('折叠后保留的草稿')
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('')
    expect(screen.getByRole('button', { name: '新对话' })).not.toHaveAttribute('aria-current')
    expect(container.querySelectorAll('.conversation-row .list-row[aria-current="true"]')).toHaveLength(0)
    expect(container.querySelector('.prototype')).not.toHaveClass('is-context-collapsed')
    expect(screen.getByRole('textbox', { name: '搜索会话' })).toHaveValue('东南亚')
    fireEvent.change(screen.getByRole('textbox', { name: '搜索会话' }), { target: { value: '' } })
    expect(container.querySelectorAll('.conversation-row')).toHaveLength(2)
  })

  it('validates creation fields and discards a cancelled draft without changing an existing conversation draft', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '原有聊天草稿' } })
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    const modal = screen.getByRole('form', { name: '创建专家' })
    const submit = within(modal).getByRole('button', { name: '创建并聊天' })
    fireEvent.click(submit)
    expect(within(modal).getByText('请输入专家名称')).toHaveAttribute('role', 'alert')
    expect(within(modal).getByText('请填写不超过 200 字的专家简介')).toHaveAttribute('role', 'alert')
    fireEvent.change(within(modal).getByRole('textbox', { name: '专家名称' }), { target: { value: '  ' } })
    fireEvent.change(within(modal).getByRole('textbox', { name: '专家简介' }), { target: { value: '   ' } })
    fireEvent.change(within(modal).getByRole('textbox', { name: '系统提示词' }), { target: { value: '   ' } })
    fireEvent.click(submit)
    expect(within(modal).getByRole('textbox', { name: '专家名称' })).toHaveAttribute('aria-invalid', 'true')
    expect(within(modal).getByText('请填写不超过 200 字的专家简介')).toBeInTheDocument()
    expect(within(modal).getByText('请填写不超过 8000 字的系统提示词')).toBeInTheDocument()
    fireEvent.click(within(modal).getByRole('button', { name: '取消' }))
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(32)
    expect(screen.queryByRole('region', { name: '我创建的' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    expect(screen.getByRole('textbox', { name: '专家名称' })).toHaveValue('')
    fireEvent.click(screen.getByRole('button', { name: '取消' }))
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('原有聊天草稿')
  })

  it('creates a searchable agent, preserves its setup and starts isolated conversations', () => {
    const create = vi.fn()
    vi.stubGlobal('aiEmployeeOS', { employee: { create } })
    const { container } = render(<App />)
    navigate('专家市场')
    fireEvent.change(screen.getByRole('textbox', { name: '搜索智能体' }), { target: { value: '不存在xyz' } })
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    fireEvent.change(screen.getByRole('textbox', { name: '专家名称' }), { target: { value: '  考研英语陪练  ' } })
    fireEvent.change(screen.getByRole('textbox', { name: '专家简介' }), { target: { value: '  陪我练习考研英语阅读，讲解长难句并整理易错词。  ' } })
    const prompt = '先问我的理解，再用例子讲解。\n每次练习后给出改进建议。'
    fireEvent.change(screen.getByRole('textbox', { name: '系统提示词' }), { target: { value: `  ${prompt}  ` } })
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByPlaceholderText('发送给考研英语陪练')).toHaveValue('')
    expect(screen.getByLabelText('对话')).toHaveTextContent('陪我练习考研英语阅读，讲解长难句并整理易错词。')
    expect(container.querySelectorAll('.conversation-row')).toHaveLength(2)
    expect(container.querySelectorAll('.conversation-row .list-row[aria-current="true"]')).toHaveLength(0)
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '一起练习阅读' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(container.querySelector('.message-block--agent')).toHaveTextContent('考研英语陪练')
    expect(container.querySelectorAll('.conversation-row')).toHaveLength(3)
    openPersonalCenter()
    navigate('专家市场')
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(33)
    const ownAgents = screen.getByRole('region', { name: '我创建的' })
    expect(within(ownAgents).getByRole('button', { name: '查看智能体 考研英语陪练' })).toBeEnabled()
    fireEvent.change(screen.getByRole('textbox', { name: '搜索智能体' }), { target: { value: '长难句' } })
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(1)
    fireEvent.click(screen.getByRole('button', { name: '查看智能体 考研英语陪练' }))
    const detail = screen.getByRole('dialog', { name: '考研英语陪练详情' })
    expect(within(detail).getByRole('heading', { name: '角色设定' })).toBeInTheDocument()
    expect(detail.querySelector('.student-agent-prompt')?.textContent).toBe(prompt)
    fireEvent.click(within(detail).getByRole('button', { name: '开始对话' }))
    expect(screen.getByPlaceholderText('发送给考研英语陪练')).toHaveValue('')
    expect(screen.getByLabelText('对话')).not.toHaveTextContent('一起练习阅读')
    fireEvent.click(screen.getByRole('button', { name: /^一起练习阅读/ }))
    expect(screen.getByLabelText('对话')).toHaveTextContent('一起练习阅读')
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('')
    expect(create).not.toHaveBeenCalled()
  })

  it('keeps a custom namesake separate from a built-in agent', () => {
    render(<App />)
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    fireEvent.change(screen.getByRole('textbox', { name: '专家名称' }), { target: { value: '高数辅导' } })
    fireEvent.change(screen.getByRole('textbox', { name: '专家简介' }), { target: { value: '只陪我复习自己的期末错题，逐题整理。' } })
    fireEvent.change(screen.getByRole('textbox', { name: '系统提示词' }), { target: { value: '先了解用户目标，再给出具体的分步建议。' } })
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByLabelText('对话')).toHaveTextContent('只陪我复习自己的期末错题，逐题整理。')
    navigate('专家市场')
    fireEvent.click(within(screen.getByRole('region', { name: '学科辅导' })).getByRole('button', { name: '查看智能体 高数辅导' }))
    fireEvent.click(screen.getByRole('button', { name: '开始对话' }))
    expect(screen.getByLabelText('对话')).toHaveTextContent('拆解微积分、极限与级数')
    expect(screen.getByLabelText('对话')).not.toHaveTextContent('只陪我复习自己的期末错题')
  })

  it('retains the full expert configuration across pages and shows opening questions in chat', () => {
    render(<App />)
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    fireEvent.change(screen.getByRole('textbox', { name: '专家名称' }), { target: { value: '课件辅导专家' } })
    fireEvent.change(screen.getByRole('textbox', { name: '专家简介' }), { target: { value: '帮助我理解课件并整理学习计划。' } })
    fireEvent.change(screen.getByRole('textbox', { name: '系统提示词' }), { target: { value: '先问学习目标，分析材料后给出复习建议。' } })
    fireEvent.change(screen.getByRole('textbox', { name: '开场白' }), { target: { value: '今天想复习哪门课？' } })
    fireEvent.change(screen.getByRole('textbox', { name: '推荐问题' }), { target: { value: '整理本周复习计划\n讲解这张课件图片' } })
    expect(screen.getByRole('complementary', { name: '专家预览' })).toHaveTextContent('今天想复习哪门课？')
    fireEvent.click(screen.getByRole('button', { name: '模型配置' }))
    fireEvent.change(screen.getByRole('combobox', { name: '运行模型' }), { target: { value: 'glm-5.2' } })
    fireEvent.change(screen.getByRole('spinbutton', { name: '最大输出 Token' }), { target: { value: '2048' } })
    fireEvent.change(screen.getByRole('spinbutton', { name: '响应超时（秒）' }), { target: { value: '60' } })
    fireEvent.click(screen.getByRole('checkbox', { name: /流式回复/ }))
    fireEvent.click(screen.getByRole('button', { name: '执行能力' }))
    fireEvent.click(screen.getByRole('button', { name: 'MCP' }))
    fireEvent.click(screen.getByRole('checkbox', { name: '添加校内文档 MCP 服务' }))
    fireEvent.click(screen.getByRole('checkbox', { name: '校内文档 MCP 服务：创建本机文档' }))
    fireEvent.click(screen.getByRole('button', { name: '输入输出' }))
    fireEvent.click(screen.getByRole('checkbox', { name: /图片/ }))
    fireEvent.click(screen.getByRole('checkbox', { name: 'Markdown' }))
    openPersonalCenter()
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    expect(screen.getByRole('textbox', { name: '专家名称' })).toHaveValue('课件辅导专家')
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByLabelText('对话')).toHaveTextContent('今天想复习哪门课？')
    fireEvent.click(screen.getByRole('button', { name: '整理本周复习计划' }))
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('整理本周复习计划')
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '查看智能体 课件辅导专家' }))
    const detail = screen.getByRole('dialog', { name: '课件辅导专家详情' })
    expect(detail).toHaveTextContent('glm-5.2 · 2048 Token · 60 秒 · 完整回复')
    expect(detail).toHaveTextContent('文字、图片')
    expect(detail).toHaveTextContent('纯文本、Markdown')
    expect(detail).toHaveTextContent('校内文档 MCP 服务 · v1')
    expect(detail).toHaveTextContent('创建本机文档（执行前由本人确认）')
    fireEvent.click(within(detail).getByRole('button', { name: '返回浏览' }))
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    expect(screen.getByRole('textbox', { name: '专家名称' })).toHaveValue('')
  })

  it('routes invalid expert settings to the right section and enforces input/model compatibility', () => {
    render(<App />)
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    fireEvent.change(screen.getByRole('textbox', { name: '专家名称' }), { target: { value: '复习专家' } })
    fireEvent.change(screen.getByRole('textbox', { name: '专家简介' }), { target: { value: '整理复习计划' } })
    fireEvent.change(screen.getByRole('textbox', { name: '系统提示词' }), { target: { value: '按学习进度安排练习。' } })
    fireEvent.change(screen.getByRole('textbox', { name: '推荐问题' }), { target: { value: '一\n二\n三\n四\n五' } })
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByRole('alert')).toHaveTextContent('推荐问题最多 4 条')
    fireEvent.change(screen.getByRole('textbox', { name: '推荐问题' }), { target: { value: '' } })
    fireEvent.click(screen.getByRole('button', { name: '模型配置' }))
    fireEvent.change(screen.getByRole('spinbutton', { name: '最大输出 Token' }), { target: { value: '' } })
    fireEvent.click(screen.getByRole('button', { name: '输入输出' }))
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByRole('spinbutton', { name: '最大输出 Token' })).toHaveAttribute('aria-invalid', 'true')
    fireEvent.change(screen.getByRole('spinbutton', { name: '最大输出 Token' }), { target: { value: '4096' } })
    fireEvent.click(screen.getByRole('button', { name: '输入输出' }))
    fireEvent.click(screen.getByRole('checkbox', { name: /图片/ }))
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByRole('alert')).toHaveTextContent('图片或音频输入需要支持相应输入的多模态模型')
    fireEvent.click(screen.getByRole('checkbox', { name: /图片/ }))
    fireEvent.click(screen.getByRole('checkbox', { name: '纯文本' }))
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByRole('alert')).toHaveTextContent('至少选择一种输出格式')
    fireEvent.click(screen.getByRole('checkbox', { name: '纯文本' }))
    fireEvent.click(screen.getByRole('button', { name: '执行能力' }))
    fireEvent.click(screen.getByRole('checkbox', { name: '添加文本分析与结构化表达' }))
    fireEvent.click(screen.getByRole('checkbox', { name: '文本分析与结构化表达：读取与分析' }))
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByRole('alert')).toHaveTextContent('每项执行能力至少选择一个可用操作')
    fireEvent.click(screen.getByRole('checkbox', { name: '添加文本分析与结构化表达' }))
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByPlaceholderText('发送给复习专家')).toBeEnabled()
  })

  it('searches the agent catalog by expertise and recovers from empty results', () => {
    render(<App />)
    fireEvent.change(screen.getByRole('textbox', { name: '搜索会话' }), { target: { value: '不存在的会话xyz' } })
    expect(screen.getByText('没有匹配的会话')).toHaveAttribute('role', 'status')
    navigate('专家市场')
    const search = screen.getByRole('textbox', { name: '搜索智能体' })
    fireEvent.change(search, { target: { value: '微积分' } })
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(1)
    fireEvent.click(screen.getByRole('button', { name: '查看智能体 高数辅导' }))
    fireEvent.click(screen.getByRole('button', { name: '返回浏览' }))
    expect(search).toHaveValue('微积分')
    fireEvent.change(search, { target: { value: '恋爱交流' } })
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(2)
    expect(screen.getByRole('button', { name: '查看智能体 恋爱专家' })).toBeEnabled()
    fireEvent.change(search, { target: { value: '不存在的智能体xyz' } })
    expect(screen.getByRole('heading', { name: '没有找到匹配的智能体' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '查看全部智能体' }))
    expect(search).toHaveValue('')
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(32)
  })

  it('combines audience, category and search filters and resets incompatible categories', () => {
    render(<App />)
    navigate('专家市场')
    const ranges = screen.getByRole('group', { name: '智能体范围' })
    const search = screen.getByRole('textbox', { name: '搜索智能体' })
    const cards = () => screen.queryAllByRole('button', { name: /^查看智能体 / })
    const categoryFilters = () => screen.getByRole('group', { name: '用途分类' })
    expect(within(ranges).getByRole('button', { name: '全部', pressed: true })).toBeInTheDocument()
    fireEvent.click(within(ranges).getByRole('button', { name: '教职工常用' }))
    expect(cards()).toHaveLength(12)
    expect(screen.queryByRole('region', { name: '学科辅导' })).not.toBeInTheDocument()
    expect(within(categoryFilters()).getAllByRole('button')).toHaveLength(5)
    fireEvent.click(within(categoryFilters()).getByRole('button', { name: '教学备课' }))
    expect(cards()).toHaveLength(3)
    fireEvent.change(search, { target: { value: '教案' } })
    expect(cards()).toHaveLength(1)
    fireEvent.click(screen.getByRole('button', { name: '查看智能体 备课教案助手' }))
    fireEvent.click(screen.getByRole('button', { name: '返回浏览' }))
    expect(search).toHaveValue('教案')
    expect(within(ranges).getByRole('button', { name: '教职工常用', pressed: true })).toBeInTheDocument()
    expect(within(categoryFilters()).getByRole('button', { name: '教学备课', pressed: true })).toBeInTheDocument()
    fireEvent.change(search, { target: { value: '' } })
    fireEvent.click(within(ranges).getByRole('button', { name: '学生常用' }))
    expect(cards()).toHaveLength(20)
    expect(within(categoryFilters()).getByRole('button', { name: '全部分类', pressed: true })).toBeInTheDocument()
    expect(within(categoryFilters()).queryByRole('button', { name: '教学备课' })).not.toBeInTheDocument()
    fireEvent.click(within(categoryFilters()).getByRole('button', { name: '游戏攻略' }))
    fireEvent.change(search, { target: { value: '教案' } })
    expect(cards()).toHaveLength(0)
    expect(screen.getByRole('heading', { name: '没有找到匹配的智能体' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '查看全部智能体' }))
    expect(search).toHaveValue('')
    expect(within(ranges).getByRole('button', { name: '全部', pressed: true })).toBeInTheDocument()
    expect(within(categoryFilters()).getByRole('button', { name: '全部分类', pressed: true })).toBeInTheDocument()
    expect(cards()).toHaveLength(32)
  })

  it('offers creation from an empty personal category and lists the created agent there', () => {
    render(<App />)
    navigate('专家市场')
    fireEvent.click(within(screen.getByRole('group', { name: '智能体范围' })).getByRole('button', { name: '我创建的' }))
    expect(screen.getByRole('heading', { name: '还没有创建专家' })).toBeInTheDocument()
    expect(screen.queryByRole('group', { name: '用途分类' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '创建专家' }))
    fireEvent.change(screen.getByRole('textbox', { name: '专家名称' }), { target: { value: '教师周计划' } })
    fireEvent.change(screen.getByRole('textbox', { name: '专家简介' }), { target: { value: '帮我按教学任务和科研安排整理每周计划。' } })
    fireEvent.change(screen.getByRole('textbox', { name: '系统提示词' }), { target: { value: '先了解用户目标，再给出具体的分步建议。' } })
    fireEvent.click(screen.getByRole('button', { name: '创建并聊天' }))
    expect(screen.getByPlaceholderText('发送给教师周计划')).toBeEnabled()
    navigate('专家市场')
    fireEvent.click(within(screen.getByRole('group', { name: '智能体范围' })).getByRole('button', { name: '我创建的' }))
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(1)
    expect(screen.getByRole('button', { name: '查看智能体 教师周计划' })).toBeInTheDocument()
    fireEvent.change(screen.getByRole('textbox', { name: '搜索智能体' }), { target: { value: '没有匹配' } })
    expect(screen.getByRole('heading', { name: '没有找到匹配的智能体' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '查看全部智能体' }))
    expect(screen.getAllByRole('button', { name: /^查看智能体 / })).toHaveLength(33)
  })

  it('keeps the empty assistant composer available after archiving all history', () => {
    render(<App />)
    while (screen.queryAllByRole('button', { name: /^归档对话 / }).length) {
      fireEvent.click(screen.getAllByRole('button', { name: /^归档对话 / })[0])
    }
    expect(screen.getByText('暂无会话')).toBeInTheDocument()
    expect(screen.queryByLabelText('飞书会议消息时间线')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    expect(screen.getByPlaceholderText('发送给助理')).toBeEnabled()
  })

  it('does not offer system file actions for fixture attachments without files', () => {
    const { container } = render(<App />)
    fireEvent.click(within(container.querySelector('.context-pane') as HTMLElement).getByRole('button', { name: /^东南亚/ }))
    const actions = within(container.querySelector('.message-attachments--agent') as HTMLElement).getAllByRole('button', { name: /^打开方式 / })
    expect(actions.length).toBeGreaterThan(0)
    for (const action of actions) expect(action).toBeDisabled()
    expect(screen.getAllByText('示例附件未提供文件，无法打开或下载。').length).toBeGreaterThan(0)
  })

  it('shows profile and usage together from a single personal center entry', () => {
    const { container } = render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '保留聊天草稿' } })
    openPersonalCenter()
    const rail = screen.getByRole('navigation', { name: '一级导航' })
    expect(within(rail.querySelector('.rail__main') as HTMLElement).getAllByRole('button').map((button) => button.getAttribute('aria-label'))).toEqual(['新对话', '专家市场', '知识库 敬请期待'])
    expect(screen.getByRole('button', { name: 'Kakarrot 用户菜单' })).toHaveAttribute('aria-current', 'page')
    expect(screen.getByRole('heading', { name: '聊天记录' })).toBeInTheDocument()
    expect(container.querySelector('.system-navigation')).toBeNull()
    expect(screen.getByRole('heading', { name: '个人中心' })).toBeInTheDocument()
    expect(screen.getByText('姓名')).toBeInTheDocument()
    expect(screen.getByText('学号')).toBeInTheDocument()
    expect(within(container.querySelector('.personal-center-page') as HTMLElement).getByText('Kakarrot')).toBeInTheDocument()
    expect(screen.getByText('20260001')).toBeInTheDocument()
    expect(within(container.querySelector('.personal-center-page') as HTMLElement).queryByRole('textbox')).not.toBeInTheDocument()
    expect(screen.getByRole('table', { name: '用量记录' })).toHaveTextContent('09-17 09:30')
    expect(screen.getByText('38,400 Token')).toBeInTheDocument()
    expect(screen.getByText('¥28.60')).toBeInTheDocument()
    expect(screen.getByText('已上报 Token')).toBeInTheDocument()
    expect(screen.getByText('平台使用余额')).toBeInTheDocument()
    expect(screen.queryByText(/积分/)).not.toBeInTheDocument()
    expect(screen.queryByRole('spinbutton', { name: '月度预算金额' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '保存预算' })).not.toBeInTheDocument()
    for (const model of ['deepseek-v4-pro', 'gpt-image-2', 'seedance-2.0']) expect(screen.queryByText(model)).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /^东南亚市场研究/ }))
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('保留聊天草稿')
    expect(screen.getByRole('button', { name: 'Kakarrot 用户菜单' })).not.toHaveAttribute('aria-current')
  })

  it('paginates all usage records without changing totals', () => {
    render(<App />)
    openPersonalCenter()
    const pagination = screen.getByRole('navigation', { name: '用量记录分页' })
    const previous = within(pagination).getByRole('button', { name: '上一页' })
    const next = within(pagination).getByRole('button', { name: '下一页' })
    const records = () => within(screen.getByRole('table', { name: '用量记录' })).getAllByRole('row').slice(1)
    const firstPage = records().map((record) => record.textContent)
    const allRecords: HTMLElement[] = []
    expect(previous).toBeDisabled()
    for (const [page, count, range] of [[1, 10, '第 1–10 条，共 23 条'], [2, 10, '第 11–20 条，共 23 条'], [3, 3, '第 21–23 条，共 23 条']] as const) {
      expect(records()).toHaveLength(count)
      expect(pagination).toHaveTextContent(range)
      expect(pagination).toHaveTextContent(`第 ${page} / 3 页`)
      expect(screen.getByText('38,400 Token')).toBeInTheDocument()
      expect(screen.getByText('¥28.60')).toBeInTheDocument()
      allRecords.push(...records())
      if (page < 3) fireEvent.click(next)
    }
    expect(next).toBeDisabled()
    expect(new Set(allRecords.map((record) => record.textContent)).size).toBe(23)
    const totalTokens = allRecords.reduce((sum, record) => sum + Number(within(record).getAllByRole('cell')[2].textContent!.replace(/[^0-9]/g, '')), 0)
    const knownAmounts = allRecords.map(record => within(record).getAllByRole('cell')[3].textContent!).filter(value => value.startsWith('¥')).map(value => Number(value.match(/¥([0-9.]+)/)![1]))
    expect(totalTokens).toBe(38400)
    expect(knownAmounts.reduce((sum, value) => sum + value, 0)).toBeCloseTo(2.44)
    fireEvent.click(previous)
    fireEvent.click(previous)
    expect(previous).toBeDisabled()
    expect(records().map((record) => record.textContent)).toEqual(firstPage)
  })

  it('uploads only the avatar and keeps name and student ID read-only across pages and chat', async () => {
    const { container } = render(<App />)
    openPersonalCenter()
    const avatarBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l1sAAAAASUVORK5CYII='
    const avatar = new File([Uint8Array.from(atob(avatarBase64), (character) => character.charCodeAt(0))], 'avatar.png', { type: 'image/png' })
    const avatarUrl = `data:image/png;base64,${avatarBase64}`
    const upload = screen.getByLabelText('从本地上传个人头像')
    expect(upload).toHaveAttribute('accept', 'image/png,image/jpeg,image/webp')
    expect(container.querySelectorAll('.personal-center-page input')).toHaveLength(1)
    expect(within(container.querySelector('.personal-center-page') as HTMLElement).queryByRole('textbox')).not.toBeInTheDocument()
    fireEvent.change(upload, { target: { files: [avatar] } })
    await waitFor(() => expect(container.querySelector('.employee-avatar-setting img')).toHaveAttribute('src', avatarUrl))
    expect(container.querySelector('.rail-profile-button img')).toHaveAttribute('src', avatarUrl)
    const personalMenu = screen.getByRole('navigation', { name: '个人中心菜单' })
    fireEvent.click(within(personalMenu).getByRole('button', { name: '归档会话' }))
    expect(screen.queryByLabelText('从本地上传个人头像')).not.toBeInTheDocument()
    fireEvent.click(within(personalMenu).getByRole('button', { name: '基本资料' }))
    expect(container.querySelector('.employee-avatar-setting img')).toHaveAttribute('src', avatarUrl)
    fireEvent.click(screen.getByRole('button', { name: '下一页' }))
    expect(within(container.querySelector('.personal-center-page') as HTMLElement).getByText('Kakarrot')).toBeInTheDocument()
    expect(screen.getByText('20260001')).toBeInTheDocument()
    navigate('新对话')
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '你好' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(container.querySelector('.message-block--user')).toHaveTextContent('Kakarrot')
    expect(container.querySelector('.message-block--user img')).toHaveAttribute('src', avatarUrl)
    openPersonalCenter()
    expect(container.querySelector('.employee-avatar-setting img')).toHaveAttribute('src', avatarUrl)
    expect(within(container.querySelector('.personal-center-page') as HTMLElement).getByText('Kakarrot')).toBeInTheDocument()
    expect(screen.getByText('20260001')).toBeInTheDocument()
    expect(within(container.querySelector('.personal-center-page') as HTMLElement).queryByRole('textbox')).not.toBeInTheDocument()
  })

  it('retains uploaded files per conversation and exposes an actual download with URL cleanup', async () => {
    const createUrl = vi.fn(() => 'blob:uploaded-file')
    const revokeUrl = vi.fn()
    vi.stubGlobal('URL', class extends URL {
      static createObjectURL = createUrl
      static revokeObjectURL = revokeUrl
    })
    const { container } = render(<App />)
    const selectResearch = () => fireEvent.click(within(container.querySelector('.context-pane') as HTMLElement).getByRole('button', { name: /^东南亚/ }))
    selectResearch()
    const file = new File(['test attachment'], 'review-note.txt', { type: 'text/plain' })
    fireEvent.change(screen.getByLabelText('添加附件'), { target: { files: [file] } })
    fireEvent.click(screen.getByRole('button', { name: /^Agent 产品讨论/ }))
    expect(screen.queryByRole('button', { name: '移除 review-note.txt' })).not.toBeInTheDocument()
    selectResearch()
    expect(screen.getByRole('button', { name: '移除 review-note.txt' })).toBeInTheDocument()
    fireEvent.submit(container.querySelector('form.composer')!)
    fireEvent.click(screen.getByRole('button', { name: '打开 review-note.txt' }))
    const preview = screen.getByRole('dialog', { name: '附件预览' })
    await waitFor(() => expect(within(preview).getByRole('link', { name: '下载文件' })).toHaveAttribute('href', 'blob:uploaded-file'))
    expect(createUrl).toHaveBeenCalledWith(file)
    expect(within(preview).getByRole('link', { name: '下载文件' })).toHaveAttribute('download', file.name)
    fireEvent.click(within(preview).getByRole('button', { name: '关闭' }))
    await waitFor(() => expect(revokeUrl).toHaveBeenCalledWith('blob:uploaded-file'))
  })

  it('defaults to assistant chat without matter, scenario or group entry points', () => {
    const { container } = render(<App />)
    expect(screen.getByRole('heading', { name: '今天，想一起做点什么？' })).toBeInTheDocument()
    expect(container.querySelector('.message-page')).toHaveClass('message-page--welcome')
    expect(screen.getByPlaceholderText('发送给助理')).toBeEnabled()
    expect(screen.getByRole('button', { name: '找专家聊天' })).toBeEnabled()
    expect(screen.queryByLabelText('当前会话事项')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /事项边栏/ })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '发起会议并生成摘要' })).not.toBeInTheDocument()
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '你好' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(container.querySelector('.message-page')).not.toHaveClass('message-page--welcome')
    expect(screen.queryByRole('group', { name: '快捷提问' })).not.toBeInTheDocument()
    expect(container.querySelector('.message-block--agent')).toHaveTextContent('助理')
    expect(container.querySelector('.message-block--agent')).toHaveTextContent('演示回复')
    expect(container.querySelector('.message-block--agent')).toHaveTextContent('尚未调用模型')
    navigate('专家市场')
    expect(screen.queryByRole('tab', { name: '专家团' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '查看智能体 高数辅导' })).toBeEnabled()
    openPersonalCenter()
    expect(screen.queryByRole('button', { name: '总管' })).not.toBeInTheDocument()
  })

  it('fills welcome suggestions without sending or replacing the existing draft and attachments', () => {
    const { container } = render(<App />)
    for (const [label, expected] of [['学习辅导', '学习目标'], ['备课办公', '教学或办公材料'], ['旅行攻略', '周末旅行'], ['聊聊心事', '陪我梳理一下感受']]) {
      navigate('新对话')
      fireEvent.click(within(screen.getByRole('group', { name: '快捷提问' })).getByRole('button', { name: label }))
      expect((screen.getByRole('textbox', { name: '发送消息' }) as HTMLTextAreaElement).value).toContain(expected)
      expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveFocus()
      expect(container.querySelectorAll('.conversation-row')).toHaveLength(2)
      expect(container.querySelectorAll('.conversation-row .list-row[aria-current="true"]')).toHaveLength(0)
    }
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '我已经写好的要求' } })
    fireEvent.change(screen.getByLabelText('添加附件'), { target: { files: [new File(['notes'], 'welcome-notes.txt', { type: 'text/plain' })] } })
    fireEvent.click(screen.getByRole('button', { name: '学习辅导' }))
    expect((screen.getByRole('textbox', { name: '发送消息' }) as HTMLTextAreaElement).value).toMatch(/^我已经写好的要求\n\n我想梳理/)
    expect(screen.getByRole('button', { name: '移除 welcome-notes.txt' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(container.querySelector('.message-page')).not.toHaveClass('message-page--welcome')
    expect(container.querySelectorAll('.conversation-row')).toHaveLength(3)
    expect(screen.getByLabelText('对话')).toHaveTextContent('我已经写好的要求')
    navigate('新对话')
    expect(container.querySelector('.message-page')).toHaveClass('message-page--welcome')
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('')
    expect(screen.queryByRole('button', { name: '移除 welcome-notes.txt' })).not.toBeInTheDocument()
  })

  it('isolates drafts, attachments and sent messages across agents and new conversations', () => {
    const { container } = render(<App />)
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '助理开场' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    const draft = screen.getByRole('textbox', { name: '发送消息' })
    fireEvent.change(draft, { target: { value: '助理专属草稿' } })
    fireEvent.change(screen.getByLabelText('添加附件'), { target: { files: [new File(['research'], 'research.txt')] } })
    navigate('专家市场')
    selectCatalogAgent('高数辅导')
    expect(screen.getByPlaceholderText('发送给高数辅导')).toHaveValue('')
    expect(screen.queryByRole('button', { name: '移除 research.txt' })).not.toBeInTheDocument()
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '高数专属消息' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(container.querySelector('.message-block--agent')).toHaveTextContent('高数辅导')
    fireEvent.click(screen.getByRole('button', { name: /^助理开场/ }))
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('助理专属草稿')
    expect(screen.getByRole('button', { name: '移除 research.txt' })).toBeInTheDocument()
    expect(screen.getByLabelText('对话')).not.toHaveTextContent('高数专属消息')
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('')
    expect(screen.queryByRole('button', { name: '移除 research.txt' })).not.toBeInTheDocument()
    expect(container.querySelector('.message-block--agent')).toBeNull()
  })

  it.each(['助理', '恋爱专家'])('adds %s to history only after sending the first message', (name) => {
    const { container } = render(<App />)
    const rows = () => container.querySelectorAll('.conversation-row')
    const selectedRows = () => container.querySelectorAll('.conversation-row .list-row[aria-current="true"]')
    expect(rows()).toHaveLength(2)
    expect(selectedRows()).toHaveLength(0)
    if (name !== '助理') {
      fireEvent.click(screen.getByRole('button', { name: '找专家聊天' }))
      selectCatalogAgent(name)
    }
    expect(screen.getByPlaceholderText(`发送给${name}`)).toBeEnabled()
    expect(rows()).toHaveLength(2)
    expect(selectedRows()).toHaveLength(0)
    const input = screen.getByRole('textbox', { name: '发送消息' })
    fireEvent.change(input, { target: { value: '尚未发送的草稿' } })
    fireEvent.change(screen.getByLabelText('添加附件'), { target: { files: [new File(['note'], 'note.txt')] } })
    expect(rows()).toHaveLength(2)
    expect(selectedRows()).toHaveLength(0)
    // Covers text with an attachment and attachment-only first messages.
    if (name !== '助理') fireEvent.change(input, { target: { value: '' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(rows()).toHaveLength(3)
    expect(selectedRows()).toHaveLength(1)
    expect(selectedRows()[0]).toHaveTextContent(name)
    fireEvent.change(input, { target: { value: '第二条消息' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(rows()).toHaveLength(3)
    const savedConversation = selectedRows()[0]
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    expect(rows()).toHaveLength(3)
    expect(selectedRows()).toHaveLength(0)
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('')
    fireEvent.click(savedConversation)
    expect(selectedRows()).toHaveLength(1)
    expect(screen.getByLabelText('对话')).toHaveTextContent('第二条消息')
  })

  it.each(['高数辅导', '王者荣耀攻略', '周末周边游', '恋爱专家', '情感陪伴专家', '学习规划师', '备课教案助手', '辅导员工作助手', '科研申报助手', '会议纪要助手'])('starts a direct conversation with %s without recruiting or calling the Runtime', (name) => {
    const detail = vi.fn()
    vi.stubGlobal('aiEmployeeOS', { employee: { detail } })
    const { container } = render(<App />)
    navigate('专家市场')
    fireEvent.click(screen.getByRole('button', { name: `查看智能体 ${name}` }))
    const modal = screen.getByRole('dialog', { name: `${name}详情` })
    expect(modal).toHaveTextContent('尚未连接模型服务')
    expect(within(modal).getByRole('button', { name: '开始对话' })).toBeEnabled()
    fireEvent.click(within(modal).getByRole('button', { name: '开始对话' }))
    expect(screen.getByPlaceholderText(`发送给${name}`)).toBeEnabled()
    expect(screen.getByRole('textbox', { name: '发送消息' })).toHaveValue('')
    fireEvent.change(screen.getByRole('textbox', { name: '发送消息' }), { target: { value: '帮我整理一下思路' } })
    fireEvent.click(screen.getByRole('button', { name: '发送' }))
    expect(container.querySelector('.message-block--agent')).toHaveTextContent(name)
    expect(container.querySelector('.message-block--agent')).toHaveTextContent('演示回复')
    expect(detail).not.toHaveBeenCalled()
    expect(screen.queryByLabelText('飞书会议消息时间线')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '新对话' }))
    expect(screen.getByPlaceholderText('发送给助理')).toHaveValue('')
    expect(container.querySelector('.message-block--agent')).toBeNull()
  })
})
