import { Book, ChatBubble, Check, Globe, Sparks } from 'iconoir-react'
import { Button, Field, Section, Tag } from './components'
import { channelLabels, experienceOf, knowledgeExamples, type AgentExperience } from './agent-experience'
import { defaultSetup } from './guided-config'
import type { AdminState, AgentConfig } from './shared'

function Toggle({ title, description, checked, change }: { title: string; description: string; checked: boolean; change: (value: boolean) => void }) {
  return <label className="agent-setting-toggle"><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" aria-label={title} checked={checked} onChange={e => change(e.target.checked)} /></label>
}

export function AgentExperienceFields({ section, config, patch, data }: { section: string; config: AgentConfig; patch: (value: Partial<AgentConfig>) => void; data: AdminState }) {
  const c = experienceOf(config)
  const update = (value: Partial<AgentExperience>) => patch({ experience: { ...c, ...value } })
  const selectKnowledge = (knowledgeIds: string[]) => patch({ experience: { ...c, knowledgeIds }, ...(knowledgeIds.length ? { setup: { ...(config.setup ?? { ...defaultSetup('custom'), promptMode: 'manual' as const, inputDescription: '用户提供的相关材料' }), resourceScope: 'selected' as const } } : {}) })
  if (section === 'welcome') return <Section title="与用户打个招呼" description="告诉使用者你能帮什么忙，让第一次提问更容易。"><Field label="开场白"><textarea aria-label="开场白" rows={3} maxLength={500} value={c.opening} placeholder="你好，我可以帮你整理材料、提取要点。把资料发给我就可以开始。" onChange={e => update({ opening: e.target.value })} /></Field><Field label="推荐问题" hint="每行一个，最多 6 个；用户点击即可开始。"><textarea aria-label="推荐问题" rows={3} value={c.questions.join('\n')} maxLength={1200} placeholder={'帮我总结这份材料\n哪些信息需要补充？'} onChange={e => update({ questions: e.target.value.split('\n').slice(0, 6) })} /></Field></Section>
  if (section === 'model') return <Section title="回答方式" description="先选适合工作的风格，再按需调整细节。"><div className="agent-style-options">{([['precise', '严谨准确', '适合制度问答、事实核对', 0.2], ['balanced', '均衡通用', '适合日常分析、整理材料', 0.5], ['creative', '灵活创意', '适合文案、头脑风暴', 0.9]] as const).map(([id, title, description, temperature]) => <button type="button" key={id} aria-pressed={c.responseStyle === id} onClick={() => update({ responseStyle: id, temperature })}><strong>{title}{c.responseStyle === id && <Check width={15} />}</strong><small>{description}</small></button>)}</div><details className="prompt-disclosure"><summary>高级模型参数</summary><div className="form-grid"><Field label="表达灵活度" hint="数值越低，回答越稳定。"><input aria-label="表达灵活度" type="number" step="0.1" min={0} max={1} value={c.temperature} onChange={e => update({ temperature: Number(e.target.value) })} /></Field><Field label="单次回答长度上限" hint="以 Token 计，属于模型参数。"><input aria-label="单次回答长度上限" type="number" min={128} max={32000} value={c.maxTokens} onChange={e => update({ maxTokens: Number(e.target.value) })} /></Field><Field label="备用模型"><select aria-label="备用模型" value={c.fallbackModel} onChange={e => update({ fallbackModel: e.target.value })}><option value="">不设置</option>{data.models.filter(m => m.modelId !== config.modelId).map(m => <option key={m.modelId}>{m.modelId}</option>)}</select></Field></div><Toggle title="逐字显示回答" description="生成过程中逐步展示内容。" checked={c.streaming} change={streaming => update({ streaming })} /></details></Section>
  if (section === 'knowledge') return <><Section title="可以参考哪些知识" description="选择知识库后，智能体可以据此回答问题。" action={<Tag>示例知识库</Tag>}><div className="agent-knowledge-list">{knowledgeExamples.map(k => <label key={k.id} className={c.knowledgeIds.includes(k.id) ? 'is-selected' : ''}><span className="agent-resource-symbol"><Book width={20} /></span><span><strong>{k.name}</strong><small>{k.description} · {k.count} 篇示例文档</small></span><input aria-label={k.name} type="checkbox" checked={c.knowledgeIds.includes(k.id)} onChange={e => selectKnowledge(e.target.checked ? [...c.knowledgeIds, k.id] : c.knowledgeIds.filter(id => id !== k.id))} /></label>)}</div><p className="muted">已选择 {c.knowledgeIds.length} 个知识库 · 本次选择用于演示，文档内容未接入。</p><Toggle title="回答附上资料来源" description="方便用户核对原文与适用条件。" checked={c.citations} change={citations => update({ citations })} /><Field label="资料中找不到答案时"><select aria-label="资料中找不到答案时" value={c.noAnswer} onChange={e => update({ noAnswer: e.target.value as AgentExperience['noAnswer'] })}><option value="ask">请用户补充资料</option><option value="explain">说明没有找到依据</option></select></Field><details className="prompt-disclosure"><summary>高级检索设置</summary><div className="form-grid"><Field label="检索方式"><select aria-label="检索方式" value={c.retrieval} onChange={e => update({ retrieval: e.target.value as AgentExperience['retrieval'] })}><option value="hybrid">混合检索（推荐）</option><option value="keyword">关键词检索</option><option value="semantic">语义检索</option></select></Field><Field label="每次参考片段数"><input aria-label="每次参考片段数" type="number" min={1} max={20} value={c.topK} onChange={e => update({ topK: Number(e.target.value) })} /></Field></div></details></Section></>
  if (section === 'input') return <Section title="用户可以提供什么" description="只开启工作需要的输入方式。"><div className="agent-choice-chips">{([['text', '文字'], ['file', '文件'], ['image', '图片'], ['audio', '音频']] as const).map(([id, label]) => <label key={id}><input type="checkbox" checked={c.modalities.includes(id)} onChange={e => update({ modalities: e.target.checked ? [...c.modalities, id] : c.modalities.filter(m => m !== id) })} />{label}</label>)}</div>{c.modalities.includes('file') && <div className="form-grid"><Field label="最多上传文件数"><input aria-label="最多上传文件数" type="number" min={1} max={10} value={c.maxFiles} onChange={e => update({ maxFiles: Number(e.target.value) })} /></Field><Field label="单个文件上限（MB）"><input aria-label="单个文件上限（MB）" type="number" min={1} max={100} value={c.maxFileSize} onChange={e => update({ maxFileSize: Number(e.target.value) })} /></Field></div>}<Field label="每次任务最多追问次数" hint="设为 0 表示不进行运行中追问。"><input aria-label="每次任务最多追问次数" type="number" min={0} max={10} value={c.followUpLimit} onChange={e => update({ followUpLimit: Number(e.target.value) })} /></Field></Section>
  if (section === 'tools') return <Section title="使用工具前如何确认"><Field label="工具操作确认"><select aria-label="工具操作确认" value={c.toolApproval} onChange={e => update({ toolApproval: e.target.value as AgentExperience['toolApproval'] })}><option value="external">发送、修改等对外操作前确认</option><option value="always">每次使用工具前都确认</option></select></Field><p className="muted">敏感操作的确认与交付结果的确认分别设置。</p></Section>
  if (section === 'output') return <Section title="结果不符合格式时"><Field label="格式不符合要求时"><select aria-label="格式不符合要求时" value={c.outputFallback} onChange={e => update({ outputFallback: e.target.value as AgentExperience['outputFallback'] })}><option value="retry">重新整理一次，再交给用户</option><option value="text">改为文字说明</option><option value="stop">停止并提示处理失败</option></select></Field></Section>
  if (section === 'memory') return <Section title="记住多少对话" description="按工作需要保留上下文，长期记忆默认关闭。"><Field label="参考最近几轮对话"><input aria-label="参考最近几轮对话" type="number" min={1} max={50} value={c.contextTurns} onChange={e => update({ contextTurns: Number(e.target.value) })} /></Field><Toggle title="跨会话记忆" description="在不同对话间记住当前用户的工作偏好。" checked={c.longTermMemory} change={longTermMemory => update({ longTermMemory })} /><Toggle title="允许用户清除记忆" description="用户可主动清除自己的会话记忆。" checked={c.clearableMemory} change={clearableMemory => update({ clearableMemory })} /></Section>
  if (section === 'access') return <><Section title="谁可以使用" description="配置使用范围，发布前再确认一次。"><Field label="使用范围"><select aria-label="使用范围" value={c.visibility} onChange={e => update({ visibility: e.target.value as AgentExperience['visibility'] })}><option value="private">仅自己</option><option value="workspace">整个工作区</option><option value="specified">指定成员或部门</option></select></Field>{c.visibility === 'specified' && <Field label="指定成员或部门" required hint="用逗号分隔成员或部门名称。"><input aria-label="指定成员或部门" value={c.audience} maxLength={500} placeholder="例如：产品部，客户服务部" onChange={e => update({ audience: e.target.value })} /></Field>}<Field label="每人每天最多使用次数"><input aria-label="每人每天最多使用次数" type="number" min={1} max={10000} value={c.dailyLimit} onChange={e => update({ dailyLimit: Number(e.target.value) })} /></Field><Toggle title="隐藏回答中的敏感信息" description="展示结果时遮盖手机号等敏感信息。" checked={c.redactSensitive} change={redactSensitive => update({ redactSensitive })} /></Section></>
  if (section === 'channels') return <Section title="从哪里使用智能体" description="先选择入口，保存并发布后展示版本对应的渠道配置。" action={<Tag>渠道演示</Tag>}><div className="agent-channel-list">{(Object.entries(channelLabels) as [keyof typeof channelLabels, string][]).map(([id, label]) => <label key={id} className={c.channelIds.includes(id) ? 'is-selected' : ''}><span className="agent-resource-symbol">{id === 'web' ? <Globe width={21} /> : id === 'api' ? <Sparks width={21} /> : <ChatBubble width={21} />}</span><span><strong>{label}</strong><small>{({ web: '通过网页打开和使用', api: '供其他应用调用', feishu: '在飞书对话中使用', wecom: '在企业微信中使用' })[id]}</small></span><input aria-label={`${label}渠道`} type="checkbox" checked={c.channelIds.includes(id)} onChange={e => update({ channelIds: e.target.checked ? [...c.channelIds, id] : c.channelIds.filter(ch => ch !== id) })} /></label>)}</div><p className="muted">渠道为配置演示，不会生成真实访问链接或连接外部应用。</p></Section>
  return null
}

export function AgentLivePreview({ config, name, onExpand }: { config: AgentConfig; name: string; onExpand: () => void }) {
  const c = experienceOf(config)
  return <aside className="agent-live-preview" aria-label="使用效果预览"><header><span><ChatBubble width={17} />使用效果</span><Tag>示例预览</Tag></header><div className="agent-preview-body"><span className="agent-preview-avatar"><Sparks width={25} /></span><h3>{name || '你的智能体'}</h3><p className="agent-preview-description">{config.description || '在左侧说明它能完成什么工作'}</p><div className="agent-preview-bubble">{c.opening || `你好，我是${name || '你的智能体'}。提供相关材料，我来帮你整理。`}</div>{c.questions.filter(Boolean).map((q, i) => <button className="agent-preview-question" key={i} onClick={onExpand}>{q}<span>↗</span></button>)}{(config.contract?.inputFields.length ?? 0) > 0 && <div className="agent-preview-form"><strong>开始前填写</strong>{config.contract!.inputFields.map(f => <div key={f.key}><span>{f.label || '未命名字段'}{f.required && <em> *</em>}</span><div>{f.help || (f.type === 'number' ? '填写数字' : f.widget === 'date' ? '选择日期' : '填写内容')}</div></div>)}</div>}</div><footer><div><span>输入</span><strong>{c.modalities.map(m => ({ text: '文字', file: '文件', image: '图片', audio: '音频' })[m]).join(' / ') || '尚未选择'}</strong></div><div><span>交付</span><strong>{({ document: '文档', table: '表格', json: '结构化数据', form: '结果表单' })[config.setup?.outputFormat ?? 'document']}</strong></div><Button onClick={onExpand}>打开交互预演</Button><small>体验填写、追问和确认流程</small></footer></aside>
}
