import { ContractFields } from './ContractFields'
import { useState } from 'react'
import { AgentExperienceFields } from './AgentExperienceFields'
import { CapabilityPicker } from './CapabilityPicker'
import { Facts, Field, Notice, Section, Tag } from './components'
import { defaultContract, contractIssues } from './agent-management'
import { defaultSetup, effectivePrompt, formatLabels } from './guided-config'
import { purposeLabels, type AdminState, type AgentAsset, type AgentConfig, type GuidedSetup } from './shared'

export const agentFieldSections = [['identity', '基本资料'], ['instructions', '工作内容'], ['resources', '模型设置'], ['knowledge', '知识库'], ['tools', '工具与技能'], ['input', '输入与追问'], ['output', '输出与验收'], ['memory', '对话与记忆'], ['limits', '运行边界'], ['access', '使用权限'], ['channels', '发布渠道']] as const
export function agentFieldSection(field: string): string {
  if (/experience.knowledgeIds/.test(field)) return 'knowledge'
  if (/experience.channelIds/.test(field)) return 'channels'
  if (/experience/.test(field)) return 'access'
  if (/input|followUp/.test(field)) return 'input'
  if (/output|outputFormat/.test(field)) return 'output'
  if (/modelId|capability|resourceScope/.test(field)) return 'resources'
  if (/memory|history/.test(field)) return 'memory'
  if (/maxSteps|timeout|approval/.test(field)) return 'limits'
  if (/name|role|description|systemPrompt|input|followUp|supplement|promptMode/.test(field)) return 'instructions'
  return 'identity'
}
export function AgentFields({ config: c, asset, patch, patchAsset, data, agentId, initialSection, disabled }: { config: AgentConfig; asset: AgentAsset; patch: (value: Partial<AgentConfig>) => void; patchAsset: (value: Partial<AgentAsset>) => void; data: AdminState; agentId: string; initialSection?: string; disabled?: boolean }) {
  const [section, setSection] = useState(initialSection || 'identity')
  const s = c.setup ?? { ...defaultSetup('custom'), promptMode: 'manual' as const, resourceScope: c.capabilityVersionIds.length ? 'selected' as const : 'provided' as const }
  const contract = c.contract ?? defaultContract()
  const updateSetup = (changes: Partial<GuidedSetup>) => patch({ setup: { ...s, ...changes } })
  const problems = contractIssues(c)
  const selected = data.capabilities.filter(cap => c.capabilityVersionIds.includes(cap.id))
  return <div className="agent-form-layout"><nav className="agent-field-nav" aria-label="配置分区">{agentFieldSections.map(([id, name], index) => <div key={id}>{[0, 2, 5, 7, 9].includes(index) && <small>{({ 0: '定义工作', 2: '资料与能力', 5: '输入与输出', 7: '行为边界', 9: '分享与发布' } as Record<number, string>)[index]}</small>}<button key={id} aria-current={section === id ? 'page' : undefined} onClick={() => setSection(id)}>{name}</button></div>)}</nav><fieldset className="agent-form-content agent-config-fieldset" disabled={disabled}>
    {section === 'identity' && <><Section title="基本信息" description="让同事一眼知道，它适合完成什么工作。"><div className="form-grid"><Field label="智能体名称" required><input aria-label="智能体名称" value={asset.name} maxLength={60} onChange={e => patchAsset({ name: e.target.value })} /></Field><Field label="负责人" required><input aria-label="负责人" value={asset.owner} maxLength={60} onChange={e => patchAsset({ owner: e.target.value })} /></Field><Field label="用途说明" className="span-2" hint="一句话介绍它能解决的问题。"><textarea aria-label="用途说明" rows={3} maxLength={500} value={asset.displayDescription} onChange={e => patchAsset({ displayDescription: e.target.value })} /></Field><Field label="分类标签" className="span-2" hint="用中文或英文逗号分隔，最多 8 个，每个不超过 20 字。"><input aria-label="分类标签" value={asset.tags.join('，')} onChange={e => patchAsset({ tags: e.target.value.split(/[,，]/) })} placeholder="例如：研究，产品，内部助手" /></Field></div><details className="prompt-disclosure"><summary>查看标识与归属</summary><Facts items={[["Agent 标识", <code>{agentId}</code>], ['工作空间', <>{data.workspace.name}<small className="block-muted">{asset.workspaceId} · 创建后固定</small></>], ['资产状态', asset.status === 'active' ? '正常' : '已归档']]} /></details></Section><Notice>工作目标在“工作内容”中维护。修改后保存为草稿，发布前可随时调整。</Notice></>}
    {section === 'instructions' && <><Section title="告诉它，如何完成工作" description="用日常语言说明目标、方法和注意事项。"><div className="form-grid"><Field label="工作目标与能力说明" required className="span-2"><textarea aria-label="工作目标与能力说明" rows={4} maxLength={500} value={c.description} onChange={e => patch({ description: e.target.value })} /></Field></div><details className="prompt-disclosure"><summary>高级身份与使用方式</summary><div className="form-grid"><Field label="运行名称" required hint="随版本冻结；目录改名不会改变它。"><input aria-label="运行名称" maxLength={20} value={c.name} onChange={e => patch({ name: e.target.value })} /></Field><Field label="使用方式"><select aria-label="使用方式" value={c.purpose} onChange={e => patch({ purpose: e.target.value as AgentConfig['purpose'] })}>{Object.entries(purposeLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field></div></details><details className="prompt-disclosure"><summary>职责摘要</summary><Field label="专业职责摘要" hint="兼容现有协作配置的简短职责，创建时由目标生成。"><input aria-label="专业职责摘要" maxLength={40} value={c.role} onChange={e => patch({ role: e.target.value })} /></Field></details><Field label="指令来源"><select aria-label="指令来源" value={s.promptMode} onChange={e => {
      const promptMode = e.target.value as GuidedSetup['promptMode']
      if (promptMode === 'guided' && !window.confirm('改为按字段生成后，会替换手写指令。继续切换？')) return
      patch({ setup: { ...s, promptMode }, systemPrompt: effectivePrompt(c) })
    }}><option value="guided">根据工作配置生成</option><option value="manual">内联手写指令</option></select></Field>{s.promptMode === 'manual' ? <Field label="工作指令" required><textarea aria-label="工作指令" className="prompt-input" rows={8} maxLength={10000} value={c.systemPrompt} onChange={e => patch({ systemPrompt: e.target.value })} /></Field> : <Field label="专业补充说明"><textarea aria-label="专业补充说明" rows={3} maxLength={5000} value={s.supplement} onChange={e => updateSetup({ supplement: e.target.value })} /></Field>}<details className="prompt-disclosure"><summary>最终工作指令 · 只读预览</summary><pre className="prompt-display">{effectivePrompt(c)}</pre></details></Section><AgentExperienceFields section="welcome" config={c} patch={patch} data={data} /></>}
    {section === 'input' && <><AgentExperienceFields section="input" config={c} patch={patch} data={data} /><Section title="开始前，需要用户填写什么" description="把常用信息做成表单，减少来回确认。"><Field label="所需资料" required><textarea aria-label="所需资料" rows={3} maxLength={2000} value={s.inputDescription} onChange={e => updateSetup({ inputDescription: e.target.value })} /></Field><Field label="缺少必要输入时"><select aria-label="缺少必要输入时" value={contract.missingInputPolicy} onChange={e => patch({ contract: { ...contract, missingInputPolicy: e.target.value as 'ask' | 'reject' } })}><option value="ask">请求补充；入口不支持追问时返回缺失项</option><option value="reject">停止并返回缺失项</option></select></Field><ContractFields label="输入" fields={contract.inputFields} onChange={inputFields => patch({ contract: { ...contract, inputFields } })} /><details className="prompt-disclosure"><summary>运行中可能需要补充什么</summary><ContractFields label="补充" fields={contract.followUpFields ?? []} onChange={followUpFields => patch({ contract: { ...contract, followUpFields } })} /></details></Section></>}
    {section === 'resources' && <><Section title="模型连接" description="引用工作区模型目录；此后台原型尚未连接模型，不收集密钥。"><Field label="运行模型"><select aria-label="运行模型" value={c.modelId} onChange={e => patch({ modelId: e.target.value as AgentConfig['modelId'] })}>{data.models.map(m => <option key={m.modelId} value={m.modelId}>{m.modelId} · {m.provider}</option>)}</select></Field></Section><AgentExperienceFields section="model" config={c} patch={patch} data={data} /></>}
    {section === 'tools' && <><Section title="能力绑定" description="选择已有能力包版本，展开查看它带来的 Skill、工具、MCP 和权限需求。"><Field label="资料范围"><select aria-label="资料范围" value={s.resourceScope} onChange={e => { const resourceScope = e.target.value as GuidedSetup['resourceScope']; patch({ setup: { ...s, resourceScope }, ...(resourceScope === 'provided' ? { ...(c.experience ? { experience: { ...c.experience, knowledgeIds: [] } } : {}), capabilityVersionIds: c.capabilityVersionIds.filter(id => data.capabilities.some(cap => cap.id === id && !cap.toolVersionIds.length && !cap.mcpVersionIds.length && !cap.permissionRequirements.length)) } : {}) }) }}><option value="provided">仅用户提供的材料（移除知识库与外部能力）</option><option value="selected">本次材料与所选能力的获准资源</option></select></Field><CapabilityPicker capabilities={s.resourceScope === 'provided' ? data.capabilities.filter(cap => !cap.toolVersionIds.length && !cap.mcpVersionIds.length && !cap.permissionRequirements.length) : data.capabilities} selectedIds={c.capabilityVersionIds} onChange={capabilityVersionIds => patch({ capabilityVersionIds })} />{selected.map(cap => <details key={cap.id} className="prompt-disclosure"><summary>{cap.name} · v{cap.version} · 依赖明细</summary><Facts items={[["能力版本", <code>{cap.id}</code>], ['Skill', cap.skillVersionIds.join('、') || '无'], ['工具', cap.toolVersionIds.join('、') || '无'], ['MCP', cap.mcpVersionIds.join('、') || '无'], ['所需权限', cap.permissionRequirements.join('、') || '无外部权限需求']]} /></details>)}<Notice>能力绑定表达配置需求，不等于执行授权。逐工具身份、凭证与审批由部署和执行器落实。</Notice></Section><AgentExperienceFields section="tools" config={c} patch={patch} data={data} /></>}
    {section === 'output' && <><Section title="输出与验收" description="先定义交付内容；需要系统消费结果时，再约定结构化字段。"><Field label="结果形式"><select aria-label="结果形式" value={s.outputFormat} onChange={e => updateSetup({ outputFormat: e.target.value as GuidedSetup['outputFormat'] })}>{Object.entries(formatLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><Field label="交付与验收要求" required><textarea aria-label="交付与验收要求" rows={5} maxLength={2000} value={c.output} onChange={e => patch({ output: e.target.value })} /></Field>{(s.outputFormat !== 'document' || contract.outputFields.length > 0) && <ContractFields label="输出" fields={contract.outputFields} onChange={outputFields => patch({ contract: { ...contract, outputFields } })} />}<Notice>字段结构会进入版本快照和指令预览。真实模型输出校验尚未接入。</Notice></Section><AgentExperienceFields section="output" config={c} patch={patch} data={data} /></>}
    {section === 'limits' && <><Section title="运行与确认" description="这些是待执行器落实的配置要求，原型不执行额度扣减或真实审批。"><div className="form-grid"><Field label="执行步骤上限" hint="单次任务的配置上限，不等同于全部模型请求次数。"><input aria-label="执行步骤上限" type="number" min={1} max={200} value={c.maxSteps} onChange={e => patch({ maxSteps: Number(e.target.value) })} /></Field><Field label="任务时限（秒）"><input aria-label="任务时限（秒）" type="number" min={1} max={3600} value={c.timeoutSeconds} onChange={e => patch({ timeoutSeconds: Number(e.target.value) })} /></Field><Field label="交付确认" className="span-2"><select aria-label="交付确认" value={s.approval} onChange={e => updateSetup({ approval: e.target.value as GuidedSetup['approval'] })}><option value="delivery">交付前确认；对外操作单独确认</option><option value="external">分析结果直接展示；对外操作必须确认</option></select></Field></div></Section></>}
    {section === 'memory' && <><AgentExperienceFields section="memory" config={c} patch={patch} data={data} /><Section title="历史与记忆"><Field label="历史依赖声明" hint="这里只声明是否依赖历史。会话标识、隔离与保留期限属于部署。"><select aria-label="历史依赖声明" value={contract.historyRequirement} onChange={e => patch({ contract: { ...contract, historyRequirement: e.target.value as 'optional' | 'required' | 'forbidden' } })}><option value="optional">可选：无历史也能执行</option><option value="required">必需：缺少历史不能执行</option><option value="forbidden">禁止：只接受本次输入</option></select></Field><div className="field-label">允许读取的上下文范围</div><div className="check-options">{[['task', '本次任务'], ['employee', '此 Agent 的记忆'], ['global', '工作区共享记忆']].map(([id, label]) => <label key={id}><input type="checkbox" checked={c.memoryScopes.includes(id as 'task')} onChange={e => patch({ memoryScopes: e.target.checked ? [...c.memoryScopes, id as 'task'] : c.memoryScopes.filter(s => s !== id) })} />{label}</label>)}</div></Section></>}
    {['knowledge', 'access', 'channels'].includes(section) && <AgentExperienceFields section={section} config={c} patch={patch} data={data} />}
    {problems.length > 0 && <Notice tone="error"><strong>字段定义需要调整</strong><ul>{problems.map((p, i) => <li key={i}>{p.message}</li>)}</ul></Notice>}
  </fieldset></div>
}
