import { useRef, useState } from 'react'
import { Button, Empty, Facts, Field, Modal, Notice, SearchField, Section, Tag, formatTime } from './components'
import { prototypeStore } from './prototype-store'
import { demoRelayResponse, modelAvailable, modelCenterOf, modelKey, modelReferences, type ModelCenterAction, type RelayModel, type RelayService } from './model-center'
import type { Actor, CampusState } from './campus/model'
import './model-center.css'

export function ModelCenter({ state, reload, notify, navigate }: { state: CampusState; reload: () => Promise<void>; notify: (text: string) => void; navigate: (path: string) => void }) {
  const [actor] = useState<Actor>(() => { try { return JSON.parse(sessionStorage.getItem('campus-demo-actor') ?? 'null') ?? { role: 'admin', department: '信息化处' } } catch { return { role: 'auditor', department: '' } } })
  const center = modelCenterOf(state); const service = center.service
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [retryRead, setRetryRead] = useState(false)
  const [modal, setModal] = useState<{ type: 'service' | 'model' | 'status'; model?: RelayModel; enabled?: boolean }>()
  const lock = useRef(false); const canManage = actor.role === 'admin'; const blocked = busy || retryRead
  const rows = center.models.filter(m => `${m.modelId} ${m.displayName}`.toLowerCase().includes(query.trim().toLowerCase()) && (filter === 'all' || filter === 'enabled' && modelAvailable(center, m) || filter === 'disabled' && !m.enabled || filter === 'offline' && (!m.upstreamAvailable || m.providerId !== service.id)))
  const [page, setPage] = useState(0); const pages = Math.max(1, Math.ceil(rows.length / 8)); const currentPage = Math.min(page, pages - 1)
  const close = () => { if (!busy) { setModal(undefined); if (!retryRead) setError('') } }
  const commit = async (action: ModelCenterAction) => {
    if (lock.current || retryRead) return
    lock.current = true; setBusy(true); setError(''); let persisted = false
    try { prototypeStore().modelCenterAction(state.revision, actor, action); persisted = true; setModal(undefined); await reload(); notify(action.type === 'sync-demo' ? '演示模型列表已更新，请配置并启用需要的模型' : '模型管理配置已保存') }
    catch (e) { if (persisted) { setRetryRead(true); setError('修改已保存，但页面读取失败。请重新读取，避免重复操作。') } else setError(e instanceof Error ? e.message : '操作失败，请重试') }
    finally { lock.current = false; setBusy(false) }
  }
  return <div className="model-center">
    <Notice>当前为接入原型：模型列表采用演示响应，尚未请求真实中转站。生产环境由服务端同步模型并保管 API Key。</Notice>
    {error && !modal && <Notice tone="error">{error}{retryRead && <Button disabled={busy} onClick={async () => { setBusy(true); try { await reload(); setRetryRead(false); setError('') } catch { setError('读取失败，请重试；已保存内容不会重复提交。') } finally { setBusy(false) } }}>重新读取</Button>}</Notice>}
    <Section title="自建中转站" description="统一接入模型服务，管理员选择哪些模型可供 Agent 使用。" action={canManage && <div className="model-row-actions"><Button disabled={blocked} onClick={() => setModal({ type: 'service' })}>配置中转站</Button><Button disabled={blocked || !service.baseUrl || !service.credentialRef || !service.enabled} variant="primary" onClick={() => void commit({ type: 'sync-demo', response: demoRelayResponse })}>同步模型（演示）</Button><Button variant="ghost" disabled={blocked} onClick={() => setModal({ type: 'status', enabled: !service.enabled })}>{service.enabled ? '停用中转站' : '启用中转站'}</Button></div>}>
      <Facts items={[["中转站名称", service.name], ['Base URL', service.baseUrl || '尚未配置']]} />
      <p className="record-note">{service.enabled ? '目录已启用' : '目录已停用'} · OpenAI 兼容 · 最近演示同步：{center.lastSyncAt ? formatTime(center.lastSyncAt) : '尚未同步'}</p>
    </Section>
    <Section title="模型列表" description="启用的模型会出现在智能体的模型选择中。新同步模型默认未启用。" action={<Button disabled={!center.models.some(m => modelAvailable(center, m)) || !canManage} onClick={() => navigate('/agents/new/expert')}>创建专家</Button>}>
      <div className="table-toolbar"><SearchField label="搜索模型" value={query} onChange={value => { setQuery(value); setPage(0) }} placeholder="搜索模型名称或 ID" /><select aria-label="模型状态筛选" value={filter} onChange={e => { setFilter(e.target.value); setPage(0) }}><option value="all">全部状态</option><option value="enabled">可供选择</option><option value="disabled">未启用</option><option value="offline">已下线</option></select></div>
      {rows.length ? <div className="table-scroll"><table className="data-table model-table"><thead><tr><th>模型名称 / ID</th><th>支持能力</th><th>状态</th><th>引用专家</th><th>操作</th></tr></thead><tbody>{rows.slice(currentPage * 8, currentPage * 8 + 8).map(model => <tr key={modelKey(model)}><td><strong>{model.displayName}</strong>{model.displayName !== model.modelId && <small>{model.modelId}</small>}<small>演示数据{model.providerId !== service.id ? ' · 原中转站' : ''}</small></td><td>{model.inputTypes.map(t => ({ text: '文本', image: '图片', audio: '音频' })[t]).join(' / ')}<small>{model.supportsTools ? '支持工具调用' : '未确认工具调用能力'}</small></td><td><Tag>{!model.upstreamAvailable || model.providerId !== service.id ? '已下线' : !service.enabled ? '中转站停用' : model.enabled ? '已启用' : '未启用'}</Tag></td><td>{modelReferences(state, model).length} 位</td><td><div className="model-row-actions"><Button variant="ghost" disabled={!canManage || blocked} aria-label={`配置模型 ${model.modelId}${model.providerId !== service.id ? '（原中转站）' : ''}`} onClick={() => setModal({ type: 'model', model })}>配置</Button><Button variant="ghost" disabled={!canManage || blocked || !model.enabled && (!service.enabled || !model.upstreamAvailable || model.providerId !== service.id)} aria-label={`${model.enabled ? '停用' : '启用'}模型 ${model.modelId}${model.providerId !== service.id ? '（原中转站）' : ''}`}  onClick={() => setModal({ type: 'status', model, enabled: !model.enabled })}>{model.enabled ? '停用' : '启用'}</Button></div></td></tr>)}</tbody></table></div> : <Empty title="没有匹配的模型" description="配置中转站并同步模型，或调整搜索条件。" />}
      <div className="table-footer"><span>共 {rows.length} 个模型</span><div><Button disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>上一页</Button><span>{currentPage + 1} / {pages}</span><Button disabled={currentPage + 1 === pages} onClick={() => setPage(currentPage + 1)}>下一页</Button></div></div>
    </Section>
    {modal?.type === 'service' && <ServiceDialog error={error} service={service} busy={blocked} close={close} save={action => void commit(action)} />}
    {modal?.type === 'model' && modal.model && <ModelDialog error={error} model={modal.model} busy={blocked} close={close} save={action => void commit(action)} />}
    {modal?.type === 'status' && <Modal title={`${modal.enabled ? '启用' : '停用'}${modal.model ? '模型' : '中转站'}`} onClose={close}>{error && <Notice tone="error">{error}</Notice>}<p>{modal.enabled ? '启用后，可用模型可供管理员配置 Agent。' : `停用后不能选择或发布使用该模型的专家。已有草稿和历史版本保留。${modal.model ? `当前有 ${modelReferences(state, modal.model).length} 位专家引用。` : ''}`}</p><footer><Button disabled={blocked} onClick={close}>取消</Button><Button disabled={blocked} variant={modal.enabled ? 'primary' : 'danger'} onClick={() => void commit(modal.model ? { type: 'model-status', providerId: modal.model.providerId, modelId: modal.model.modelId, enabled: !!modal.enabled } : { type: 'service-status', enabled: !!modal.enabled })}>确认{modal.enabled ? '启用' : '停用'}</Button></footer></Modal>}
  </div>
}
function ServiceDialog({ error, service, busy, close, save }: { error: string; service: RelayService; busy: boolean; close: () => void; save: (action: ModelCenterAction) => void }) {
  const [name, setName] = useState(service.name); const [baseUrl, setBaseUrl] = useState(service.baseUrl); const [credentialRef, setCredentialRef] = useState(service.credentialRef)
  return <Modal title="配置中转站" onClose={close}>{error && <Notice tone="error">{error}</Notice>}<Field label="中转站名称" required><input aria-label="中转站名称" maxLength={60} value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Base URL" required hint="例如 https://relay.example.com/v1，模型列表读取该地址下的 /models。"><input aria-label="Base URL" placeholder="https://relay.example.com/v1" value={baseUrl} onChange={e => setBaseUrl(e.target.value)} /></Field><Field label="服务端凭证引用" required hint="仅填写服务端保存密钥的引用名，勿填写真实 API Key。"><input aria-label="服务端凭证引用" placeholder="RELAY_API_KEY" value={credentialRef} onChange={e => setCredentialRef(e.target.value)} /></Field><p className="record-note">修改地址后须重新同步模型并重新选择 Agent 模型，已有版本保持原绑定。本页仅保存接入配置，不验证连接。</p><footer><Button disabled={busy} onClick={close}>取消</Button><Button variant="primary" disabled={busy || !name.trim() || !baseUrl.trim() || !credentialRef.trim()} onClick={() => save({ type: 'service-save', name, baseUrl, credentialRef })}>保存中转站</Button></footer></Modal>
}
function ModelDialog({ error, model, busy, close, save }: { error: string; model: RelayModel; busy: boolean; close: () => void; save: (action: ModelCenterAction) => void }) {
  const [name, setName] = useState(model.displayName); const [types, setTypes] = useState(model.inputTypes); const [tools, setTools] = useState(model.supportsTools)
  return <Modal title="配置模型" onClose={close}>{error && <Notice tone="error">{error}</Notice>}<Facts items={[["模型 ID", model.modelId], ['来源', '中转站 API 目录（当前为演示数据）']]} /><Field label="模型展示名称" required><input aria-label="模型展示名称" value={name} maxLength={100} onChange={e => setName(e.target.value)} /></Field><p>按实际模型能力配置，不根据模型名称自动推断。</p><fieldset className="model-capability-options"><legend>模型能力</legend><label><input type="checkbox" checked disabled />文本输入</label>{(['image', 'audio'] as const).map(type => <label key={type}><input type="checkbox" checked={types.includes(type)} onChange={e => setTypes(e.target.checked ? [...types, type] : types.filter(t => t !== type))} />{type === 'image' ? '图片输入' : '音频输入'}</label>)}<label><input type="checkbox" checked={tools} onChange={e => setTools(e.target.checked)} />工具调用（Tool Calling）</label></fieldset><footer><Button disabled={busy} onClick={close}>取消</Button><Button variant="primary" disabled={busy || !name.trim()} onClick={() => save({ type: 'model-edit', providerId: model.providerId, modelId: model.modelId, displayName: name, inputTypes: types, supportsTools: tools })}>保存模型</Button></footer></Modal>
}
