import { useState } from 'react'
import { ArrowRight, RefreshDouble } from 'iconoir-react'
import { Button, Field, Modal, Notice, Section } from './components'
import type { AdminState } from './shared'

export function ModelExamples({ data }: { data: AdminState }) {
  const [models, setModels] = useState(data.models.map(m => ({ ...m, enabled: true, name: m.provider === 'deepseek' ? 'DeepSeek 文本服务' : 'Poe 文本服务', baseUrl: m.provider === 'deepseek' ? 'https://api.deepseek.com' : 'https://api.poe.com' })))
  const [editing, setEditing] = useState<typeof models[number]>(); const [verified, setVerified] = useState(false)
  return <Section title="模型服务" description="配置与启停仅用于界面演示，不连接外部服务。"><div className="table-scroll"><table className="data-table"><thead><tr><th>服务名称</th><th>模型</th><th>状态</th><th>操作</th></tr></thead><tbody>{models.map(m => <tr key={m.modelId}><td><strong>{m.name}</strong><p>{m.baseUrl}</p></td><td>{m.modelId}</td><td><span className={`badge ${m.enabled ? 'badge--published' : 'badge--disabled'}`}><i />{m.enabled ? '示例启用' : '示例停用'}</span></td><td><Button variant="ghost" onClick={() => { setEditing({ ...m }); setVerified(false) }}>配置服务<ArrowRight width={14} /></Button></td></tr>)}</tbody></table></div>{editing && <Modal title="模型服务配置" onClose={() => setEditing(undefined)}><Field label="服务名称"><input aria-label="服务名称" value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></Field><Field label="服务地址"><input aria-label="服务地址" value={editing.baseUrl} onChange={e => setEditing({ ...editing, baseUrl: e.target.value })} /></Field><Field label="凭据状态" hint="原型不采集真实密钥"><input readOnly value="示例凭据 · 不用于实际连接" /></Field><div className="check-options"><label><input type="checkbox" checked={editing.enabled} onChange={e => setEditing({ ...editing, enabled: e.target.checked })} />在工作区启用</label></div>{verified && <Notice tone="success">演示连接检查通过。未发送网络请求。</Notice>}<footer><Button icon={RefreshDouble} onClick={() => setVerified(true)}>演示连接检查</Button><Button variant="primary" disabled={!editing.name.trim() || !editing.baseUrl.trim()} onClick={() => { setModels(items => items.map(m => m.modelId === editing.modelId ? editing : m)); setEditing(undefined) }}>保存配置</Button></footer></Modal>}</Section>
}
